# SPDX-License-Identifier: GPL-2.0-or-later
"""Launcher texts added with online co-op and Add to Steam (see bbport_lang.py). Russian is
listed here too, since these texts have no Russian next to them in the launcher."""

MORE_KEYS = [
    'Online co-op',
    "Messages, bloodstains and ghosts come from The Hunter's Dream; bells and summons go through a shadNet server.",
    'Play online',
    'Off: the game stays offline, as before.',
    'Game server (messages, bloodstains, ghosts)',
    'Game server',
    "The Hunter's Dream by default. Only the name is needed; the game picks the ports.",
    'Co-op server (bells and summons)',
    'Server address',
    'srv.shadps4.net:31313 is the public shadPS4 server. For a private server, enter host:port from the person who runs it.',
    'WebAPI address',
    'Of the shadNet server, not the game server. Leave empty: the server address with port 31315 is used.',
    'Account',
    'Online ID (NPID)',
    'Your shadNet account name, not your email. Register one at shadnet.shadps4.net, or ask the owner of a private server.',
    'Password',
    'Saved on this PC with the other launcher settings.',
    'Connection',
    'UPnP (open a port on the router automatically)',
    'Turn it off on Tailscale or another VPN.',
    'Everyone in a session needs the same game version (1.09) and the same server. Cheats change the game for the other players too: turn them off when you play together.',
    'Online',
    'Offline',
    'Bloodborne is in your Steam library. It starts with the settings saved in this launcher.',
    'An online account is filled in, but "Play online" is off.\n\nYes: play online.   No: play offline.',
    'The Online ID is the account name (NPID) you registered on the server, not your email address.',
    'Steam was not found on this PC (or nobody has signed in to it yet).',
    'Game server {0}: reachable',
    'Server {0}: reachable',
    'Checking…',
    'Test connection',
    'Steam has to close while the game is added; it starts again afterwards. Close Steam now?',
    'Steam did not close. Close it yourself and try again.',
    'Game server {0}: not reachable ({1})',
    'Server {0}: not reachable ({1})',
    'WebAPI {0}: reachable',
    'WebAPI {0}: answered, but it is not a shadNet server',
    'WebAPI {0}: not reachable ({1})',
    'by Super Medo',
    'Add to Steam',
    'The WebAPI box holds the game server address; it is ignored.',
    '"Play online" is off: the game starts offline.',
    'Could not add the game to Steam: {}',
    'Button prompts',
    "PlayStation (the game's own)",
    'Keyboard',
    'Xbox and Switch prompts by Dommo (Nexus Mods); keyboard prompts show the default keys. Applied at the next start.',
    'Gestures menu without the motion-control icons',
    'By Dommo (Nexus Mods).',
]

MORE = {
    'ru': [
        'Онлайн-кооператив',
        "Сообщения, пятна крови и призраки приходят с сервера The Hunter's Dream; колокола и призывы идут через сервер shadNet.",
        'Играть онлайн',
        'Выключено: игра остаётся офлайн, как раньше.',
        'Игровой сервер (сообщения, пятна крови, призраки)',
        'Игровой сервер',
        "По умолчанию The Hunter's Dream. Нужно только имя, порты игра выберет сама.",
        'Сервер кооператива (колокола и призывы)',
        'Адрес сервера',
        'srv.shadps4.net:31313 — публичный сервер shadPS4. Для частного сервера введите host:port от его владельца.',
        'Адрес WebAPI',
        'Сервера shadNet, а не игрового сервера. Оставьте пустым: будет использован адрес сервера с портом 31315.',
        'Учётная запись',
        'Онлайн-ID (NPID)',
        'Имя вашей учётной записи shadNet, а не почта. Зарегистрируйтесь на shadnet.shadps4.net или спросите владельца частного сервера.',
        'Пароль',
        'Хранится на этом ПК вместе с остальными настройками лаунчера.',
        'Подключение',
        'UPnP (автоматически открыть порт на роутере)',
        'Выключите при Tailscale или другом VPN.',
        'У всех в сессии должна быть одна версия игры (1.09) и один сервер. Читы меняют игру и для других игроков: выключайте их, когда играете вместе.',
        'Онлайн',
        'Офлайн',
        'Bloodborne добавлен в библиотеку Steam. Игра запускается с настройками, сохранёнными в этом лаунчере.',
        'Учётная запись указана, но «Играть онлайн» выключено.\n\nДа: играть онлайн.   Нет: играть офлайн.',
        'Онлайн-ID — это имя учётной записи (NPID), зарегистрированной на сервере, а не адрес почты.',
        'Steam не найден на этом ПК (или в него ещё никто не входил).',
        'Игровой сервер {0}: доступен',
        'Сервер {0}: доступен',
        'Проверка…',
        'Проверить подключение',
        'Пока игра добавляется, Steam нужно закрыть; потом он запустится снова. Закрыть Steam сейчас?',
        'Steam не закрылся. Закройте его сами и попробуйте ещё раз.',
        'Игровой сервер {0}: недоступен ({1})',
        'Сервер {0}: недоступен ({1})',
        'WebAPI {0}: доступен',
        'WebAPI {0}: отвечает, но это не сервер shadNet',
        'WebAPI {0}: недоступен ({1})',
        'автор: Super Medo',
        'Добавить в Steam',
        'В поле WebAPI указан адрес игрового сервера; он не используется.',
        '«Играть онлайн» выключено: игра запустится офлайн.',
        'Не удалось добавить игру в Steam: {}',
        'Значки кнопок',
        'PlayStation (как в игре)',
        'Клавиатура',
        'Значки Xbox и Switch от Dommo (Nexus Mods); значки клавиатуры показывают клавиши по умолчанию. Применяется при следующем запуске.',
        'Меню жестов без значков управления движением',
        'От Dommo (Nexus Mods).',
    ],
    'ar': [
        'اللعب التعاوني عبر الإنترنت',
        "الرسائل وبقع الدم والأشباح تأتي من خادم The Hunter's Dream، أما الأجراس والاستدعاء فتمر عبر خادم shadNet.",
        'العب عبر الإنترنت',
        'عند الإيقاف: تبقى اللعبة بدون إنترنت كما كانت.',
        'خادم اللعبة (الرسائل، بقع الدم، الأشباح)',
        'خادم اللعبة',
        "The Hunter's Dream افتراضيًا. يكفي الاسم فقط، واللعبة تختار المنافذ.",
        'خادم اللعب التعاوني (الأجراس والاستدعاء)',
        'عنوان الخادم',
        'srv.shadps4.net:31313 هو خادم shadPS4 العام. لخادم خاص، أدخل host:port من الشخص الذي يشغّله.',
        'عنوان WebAPI',
        'الخاص بخادم shadNet وليس خادم اللعبة. اتركه فارغًا ليُستخدم عنوان الخادم مع المنفذ 31315.',
        'الحساب',
        'المعرّف (NPID)',
        'اسم حسابك في shadNet وليس بريدك الإلكتروني. سجّل حسابًا على shadnet.shadps4.net أو اسأل صاحب الخادم الخاص.',
        'كلمة المرور',
        'تُحفظ على هذا الحاسوب مع باقي إعدادات المشغّل.',
        'الاتصال',
        'UPnP (فتح منفذ على الراوتر تلقائيًا)',
        'أوقفه عند استخدام Tailscale أو أي VPN.',
        'يجب أن يستخدم الجميع في الجلسة نفس إصدار اللعبة (1.09) ونفس الخادم. الغش يغيّر اللعبة للاعبين الآخرين أيضًا، فأوقفه عند اللعب معًا.',
        'متصل',
        'غير متصل',
        'أُضيفت Bloodborne إلى مكتبة Steam، وتعمل بالإعدادات المحفوظة في هذا المشغّل.',
        'تم إدخال حساب، لكن خيار «العب عبر الإنترنت» متوقف.\n\nنعم: العب عبر الإنترنت.   لا: العب بدون إنترنت.',
        'المعرّف هو اسم الحساب (NPID) الذي سجّلته على الخادم، وليس بريدك الإلكتروني.',
        'لم يُعثر على Steam في هذا الحاسوب (أو لم يسجّل أحد الدخول إليه بعد).',
        'خادم اللعبة {0}: متاح',
        'الخادم {0}: متاح',
        'جارٍ الفحص…',
        'اختبار الاتصال',
        'يجب إغلاق Steam أثناء إضافة اللعبة، ثم يُعاد تشغيله. هل تريد إغلاق Steam الآن؟',
        'لم يُغلق Steam. أغلقه بنفسك ثم حاول مجددًا.',
        'خادم اللعبة {0}: غير متاح ({1})',
        'الخادم {0}: غير متاح ({1})',
        'WebAPI {0}: متاح',
        'WebAPI {0}: يستجيب، لكنه ليس خادم shadNet',
        'WebAPI {0}: غير متاح ({1})',
        'بواسطة Super Medo',
        'إضافة إلى Steam',
        'حقل WebAPI يحتوي على عنوان خادم اللعبة، ولن يُستخدم.',
        'خيار «العب عبر الإنترنت» متوقف: ستبدأ اللعبة بدون إنترنت.',
        'تعذّرت إضافة اللعبة إلى Steam: {}',
        'رموز الأزرار',
        'PlayStation (رموز اللعبة الأصلية)',
        'لوحة المفاتيح',
        'رموز Xbox وSwitch من Dommo (Nexus Mods)؛ رموز لوحة المفاتيح تعرض المفاتيح الافتراضية. يُطبَّق عند التشغيل التالي.',
        'قائمة الإيماءات بدون رموز التحكم بالحركة',
        'من Dommo (Nexus Mods).',
    ],
    'es': [
        'Cooperativo en línea',
        "Los mensajes, manchas de sangre y fantasmas vienen de The Hunter's Dream; las campanas y las invocaciones pasan por un servidor shadNet.",
        'Jugar en línea',
        'Desactivado: el juego sigue sin conexión, como antes.',
        'Servidor del juego (mensajes, manchas de sangre, fantasmas)',
        'Servidor del juego',
        "The Hunter's Dream por defecto. Basta con el nombre; el juego elige los puertos.",
        'Servidor cooperativo (campanas e invocaciones)',
        'Dirección del servidor',
        'srv.shadps4.net:31313 es el servidor público de shadPS4. Para un servidor privado, escribe el host:puerto que te dé quien lo gestiona.',
        'Dirección WebAPI',
        'La del servidor shadNet, no la del servidor del juego. Déjala vacía: se usa la dirección del servidor con el puerto 31315.',
        'Cuenta',
        'ID en línea (NPID)',
        'El nombre de tu cuenta shadNet, no tu correo. Regístrate en shadnet.shadps4.net o pídesela al dueño de un servidor privado.',
        'Contraseña',
        'Se guarda en este PC con el resto de ajustes del lanzador.',
        'Conexión',
        'UPnP (abrir un puerto en el router automáticamente)',
        'Desactívalo con Tailscale u otra VPN.',
        'Todos en la sesión necesitan la misma versión del juego (1.09) y el mismo servidor. Los trucos cambian el juego también para los demás: desactívalos cuando juguéis juntos.',
        'En línea',
        'Sin conexión',
        'Bloodborne está en tu biblioteca de Steam. Se inicia con los ajustes guardados en este lanzador.',
        'Hay una cuenta en línea, pero «Jugar en línea» está desactivado.\n\nSí: jugar en línea.   No: jugar sin conexión.',
        'El ID en línea es el nombre de cuenta (NPID) que registraste en el servidor, no tu correo.',
        'No se encontró Steam en este PC (o nadie ha iniciado sesión todavía).',
        'Servidor del juego {0}: accesible',
        'Servidor {0}: accesible',
        'Comprobando…',
        'Probar la conexión',
        'Steam debe cerrarse mientras se añade el juego; después se vuelve a abrir. ¿Cerrar Steam ahora?',
        'Steam no se cerró. Ciérralo tú y vuelve a intentarlo.',
        'Servidor del juego {0}: no accesible ({1})',
        'Servidor {0}: no accesible ({1})',
        'WebAPI {0}: accesible',
        'WebAPI {0}: responde, pero no es un servidor shadNet',
        'WebAPI {0}: no accesible ({1})',
        'por Super Medo',
        'Añadir a Steam',
        'El campo WebAPI contiene la dirección del servidor del juego; se ignora.',
        '«Jugar en línea» está desactivado: el juego se inicia sin conexión.',
        'No se pudo añadir el juego a Steam: {}',
        'Iconos de botones',
        'PlayStation (los del juego)',
        'Teclado',
        'Iconos de Xbox y Switch de Dommo (Nexus Mods); los de teclado muestran las teclas por defecto. Se aplica en el próximo inicio.',
        'Menú de gestos sin iconos de control por movimiento',
        'De Dommo (Nexus Mods).',
    ],
    'pt': [
        'Cooperativo online',
        "Mensagens, manchas de sangue e fantasmas vêm do The Hunter's Dream; sinos e invocações passam por um servidor shadNet.",
        'Jogar online',
        'Desligado: o jogo continua offline, como antes.',
        'Servidor do jogo (mensagens, manchas de sangue, fantasmas)',
        'Servidor do jogo',
        "The Hunter's Dream por padrão. Basta o nome; o jogo escolhe as portas.",
        'Servidor cooperativo (sinos e invocações)',
        'Endereço do servidor',
        'srv.shadps4.net:31313 é o servidor público do shadPS4. Para um servidor privado, digite o host:porta de quem o administra.',
        'Endereço WebAPI',
        'Do servidor shadNet, não do servidor do jogo. Deixe vazio: é usado o endereço do servidor com a porta 31315.',
        'Conta',
        'ID online (NPID)',
        'O nome da sua conta shadNet, não o seu e-mail. Registre-se em shadnet.shadps4.net ou peça ao dono de um servidor privado.',
        'Senha',
        'Salva neste PC com as outras configurações do launcher.',
        'Conexão',
        'UPnP (abrir uma porta no roteador automaticamente)',
        'Desligue com Tailscale ou outra VPN.',
        'Todos na sessão precisam da mesma versão do jogo (1.09) e do mesmo servidor. Trapaças mudam o jogo para os outros jogadores também: desligue-as quando jogarem juntos.',
        'Online',
        'Offline',
        'Bloodborne está na sua biblioteca da Steam. Ele abre com as configurações salvas neste launcher.',
        'Uma conta online está preenchida, mas "Jogar online" está desligado.\n\nSim: jogar online.   Não: jogar offline.',
        'O ID online é o nome da conta (NPID) registrada no servidor, não o seu e-mail.',
        'A Steam não foi encontrada neste PC (ou ninguém entrou nela ainda).',
        'Servidor do jogo {0}: acessível',
        'Servidor {0}: acessível',
        'Verificando…',
        'Testar conexão',
        'A Steam precisa fechar enquanto o jogo é adicionado; depois ela abre de novo. Fechar a Steam agora?',
        'A Steam não fechou. Feche-a você mesmo e tente de novo.',
        'Servidor do jogo {0}: inacessível ({1})',
        'Servidor {0}: inacessível ({1})',
        'WebAPI {0}: acessível',
        'WebAPI {0}: respondeu, mas não é um servidor shadNet',
        'WebAPI {0}: inacessível ({1})',
        'por Super Medo',
        'Adicionar à Steam',
        'O campo WebAPI contém o endereço do servidor do jogo; ele é ignorado.',
        '"Jogar online" está desligado: o jogo abre offline.',
        'Não foi possível adicionar o jogo à Steam: {}',
        'Ícones dos botões',
        'PlayStation (os do jogo)',
        'Teclado',
        'Ícones de Xbox e Switch por Dommo (Nexus Mods); os de teclado mostram as teclas padrão. Aplicado na próxima inicialização.',
        'Menu de gestos sem ícones de controle por movimento',
        'Por Dommo (Nexus Mods).',
    ],
    'fr': [
        'Coopération en ligne',
        "Les messages, taches de sang et fantômes viennent de The Hunter's Dream ; les cloches et invocations passent par un serveur shadNet.",
        'Jouer en ligne',
        'Désactivé : le jeu reste hors ligne, comme avant.',
        'Serveur du jeu (messages, taches de sang, fantômes)',
        'Serveur du jeu',
        "The Hunter's Dream par défaut. Le nom suffit ; le jeu choisit les ports.",
        'Serveur de coopération (cloches et invocations)',
        'Adresse du serveur',
        "srv.shadps4.net:31313 est le serveur public de shadPS4. Pour un serveur privé, entrez l'hôte:port donné par la personne qui le gère.",
        'Adresse WebAPI',
        "Celle du serveur shadNet, pas du serveur du jeu. Laissez vide : l'adresse du serveur avec le port 31315 est utilisée.",
        'Compte',
        'ID en ligne (NPID)',
        "Le nom de votre compte shadNet, pas votre e-mail. Inscrivez-vous sur shadnet.shadps4.net ou demandez au propriétaire d'un serveur privé.",
        'Mot de passe',
        'Enregistré sur ce PC avec les autres réglages du lanceur.',
        'Connexion',
        'UPnP (ouvrir un port sur le routeur automatiquement)',
        'Désactivez-le avec Tailscale ou un autre VPN.',
        "Tous les joueurs d'une session doivent avoir la même version du jeu (1.09) et le même serveur. Les triches changent aussi le jeu des autres : désactivez-les quand vous jouez ensemble.",
        'En ligne',
        'Hors ligne',
        'Bloodborne est dans votre bibliothèque Steam. Il démarre avec les réglages enregistrés dans ce lanceur.',
        'Un compte en ligne est renseigné, mais « Jouer en ligne » est désactivé.\n\nOui : jouer en ligne.   Non : jouer hors ligne.',
        "L'ID en ligne est le nom de compte (NPID) enregistré sur le serveur, pas votre adresse e-mail.",
        "Steam est introuvable sur ce PC (ou personne ne s'y est encore connecté).",
        'Serveur du jeu {0} : accessible',
        'Serveur {0} : accessible',
        'Vérification…',
        'Tester la connexion',
        "Steam doit être fermé pendant l'ajout du jeu ; il redémarre ensuite. Fermer Steam maintenant ?",
        "Steam ne s'est pas fermé. Fermez-le vous-même et réessayez.",
        'Serveur du jeu {0} : inaccessible ({1})',
        'Serveur {0} : inaccessible ({1})',
        'WebAPI {0} : accessible',
        "WebAPI {0} : répond, mais ce n'est pas un serveur shadNet",
        'WebAPI {0} : inaccessible ({1})',
        'par Super Medo',
        'Ajouter à Steam',
        "Le champ WebAPI contient l'adresse du serveur du jeu ; elle est ignorée.",
        '« Jouer en ligne » est désactivé : le jeu démarre hors ligne.',
        "Impossible d'ajouter le jeu à Steam : {}",
        'Icônes des boutons',
        'PlayStation (ceux du jeu)',
        'Clavier',
        'Icônes Xbox et Switch par Dommo (Nexus Mods) ; celles du clavier montrent les touches par défaut. Appliqué au prochain lancement.',
        'Menu des gestes sans icônes de détection de mouvement',
        'Par Dommo (Nexus Mods).',
    ],
    'de': [
        'Online-Koop',
        "Nachrichten, Blutflecken und Geister kommen von The Hunter's Dream; Glocken und Beschwörungen laufen über einen shadNet-Server.",
        'Online spielen',
        'Aus: Das Spiel bleibt wie bisher offline.',
        'Spielserver (Nachrichten, Blutflecken, Geister)',
        'Spielserver',
        "Standardmäßig The Hunter's Dream. Der Name genügt; die Ports wählt das Spiel.",
        'Koop-Server (Glocken und Beschwörungen)',
        'Serveradresse',
        'srv.shadps4.net:31313 ist der öffentliche shadPS4-Server. Für einen privaten Server Host:Port vom Betreiber eintragen.',
        'WebAPI-Adresse',
        'Die des shadNet-Servers, nicht des Spielservers. Leer lassen: Dann wird die Serveradresse mit Port 31315 verwendet.',
        'Konto',
        'Online-ID (NPID)',
        'Dein shadNet-Kontoname, nicht deine E-Mail. Registriere dich auf shadnet.shadps4.net oder frag den Betreiber eines privaten Servers.',
        'Passwort',
        'Wird auf diesem PC mit den anderen Launcher-Einstellungen gespeichert.',
        'Verbindung',
        'UPnP (Port am Router automatisch öffnen)',
        'Bei Tailscale oder einem anderen VPN ausschalten.',
        'Alle in einer Sitzung brauchen dieselbe Spielversion (1.09) und denselben Server. Cheats verändern das Spiel auch für die anderen: Schaltet sie beim gemeinsamen Spielen aus.',
        'Online',
        'Offline',
        'Bloodborne ist in deiner Steam-Bibliothek. Es startet mit den in diesem Launcher gespeicherten Einstellungen.',
        'Ein Online-Konto ist eingetragen, aber „Online spielen“ ist aus.\n\nJa: online spielen.   Nein: offline spielen.',
        'Die Online-ID ist der auf dem Server registrierte Kontoname (NPID), nicht deine E-Mail-Adresse.',
        'Steam wurde auf diesem PC nicht gefunden (oder es hat sich noch niemand angemeldet).',
        'Spielserver {0}: erreichbar',
        'Server {0}: erreichbar',
        'Wird geprüft…',
        'Verbindung testen',
        'Steam muss geschlossen werden, während das Spiel hinzugefügt wird; danach startet es wieder. Steam jetzt schließen?',
        'Steam wurde nicht geschlossen. Schließe es selbst und versuche es erneut.',
        'Spielserver {0}: nicht erreichbar ({1})',
        'Server {0}: nicht erreichbar ({1})',
        'WebAPI {0}: erreichbar',
        'WebAPI {0}: antwortet, ist aber kein shadNet-Server',
        'WebAPI {0}: nicht erreichbar ({1})',
        'von Super Medo',
        'Zu Steam hinzufügen',
        'Das WebAPI-Feld enthält die Adresse des Spielservers; sie wird ignoriert.',
        '„Online spielen“ ist aus: Das Spiel startet offline.',
        'Das Spiel konnte nicht zu Steam hinzugefügt werden: {}',
        'Tastensymbole',
        'PlayStation (die des Spiels)',
        'Tastatur',
        'Xbox- und Switch-Symbole von Dommo (Nexus Mods); die Tastatursymbole zeigen die Standardtasten. Wird beim nächsten Start übernommen.',
        'Gestenmenü ohne Symbole der Bewegungssteuerung',
        'Von Dommo (Nexus Mods).',
    ],
    'it': [
        'Cooperativa online',
        "Messaggi, macchie di sangue e fantasmi arrivano da The Hunter's Dream; campane ed evocazioni passano da un server shadNet.",
        'Gioca online',
        'Disattivato: il gioco resta offline, come prima.',
        'Server di gioco (messaggi, macchie di sangue, fantasmi)',
        'Server di gioco',
        "The Hunter's Dream come predefinito. Basta il nome; le porte le sceglie il gioco.",
        'Server cooperativo (campane ed evocazioni)',
        'Indirizzo del server',
        'srv.shadps4.net:31313 è il server pubblico di shadPS4. Per un server privato, inserisci host:porta forniti da chi lo gestisce.',
        'Indirizzo WebAPI',
        "Quello del server shadNet, non del server di gioco. Lascia vuoto: viene usato l'indirizzo del server con la porta 31315.",
        'Account',
        'ID online (NPID)',
        'Il nome del tuo account shadNet, non la tua email. Registrati su shadnet.shadps4.net o chiedi al proprietario di un server privato.',
        'Password',
        'Salvata su questo PC con le altre impostazioni del launcher.',
        'Connessione',
        'UPnP (apri automaticamente una porta sul router)',
        "Disattivalo con Tailscale o un'altra VPN.",
        'Tutti nella sessione devono avere la stessa versione del gioco (1.09) e lo stesso server. I trucchi cambiano il gioco anche per gli altri: disattivali quando giocate insieme.',
        'Online',
        'Offline',
        'Bloodborne è nella tua libreria di Steam. Si avvia con le impostazioni salvate in questo launcher.',
        'È inserito un account online, ma "Gioca online" è disattivato.\n\nSì: gioca online.   No: gioca offline.',
        "L'ID online è il nome dell'account (NPID) registrato sul server, non il tuo indirizzo email.",
        "Steam non è stato trovato su questo PC (o nessuno vi ha ancora effettuato l'accesso).",
        'Server di gioco {0}: raggiungibile',
        'Server {0}: raggiungibile',
        'Verifica in corso…',
        'Prova la connessione',
        'Steam deve chiudersi mentre il gioco viene aggiunto; poi si riapre. Chiudere Steam ora?',
        'Steam non si è chiuso. Chiudilo tu e riprova.',
        'Server di gioco {0}: non raggiungibile ({1})',
        'Server {0}: non raggiungibile ({1})',
        'WebAPI {0}: raggiungibile',
        'WebAPI {0}: risponde, ma non è un server shadNet',
        'WebAPI {0}: non raggiungibile ({1})',
        'di Super Medo',
        'Aggiungi a Steam',
        "Il campo WebAPI contiene l'indirizzo del server di gioco; viene ignorato.",
        '"Gioca online" è disattivato: il gioco parte offline.',
        'Impossibile aggiungere il gioco a Steam: {}',
        'Icone dei pulsanti',
        'PlayStation (quelle del gioco)',
        'Tastiera',
        'Icone Xbox e Switch di Dommo (Nexus Mods); quelle della tastiera mostrano i tasti predefiniti. Si applica al prossimo avvio.',
        'Menu dei gesti senza icone del controllo di movimento',
        'Di Dommo (Nexus Mods).',
    ],
    'pl': [
        'Kooperacja online',
        "Wiadomości, plamy krwi i duchy pochodzą z The Hunter's Dream; dzwony i przywołania idą przez serwer shadNet.",
        'Graj online',
        'Wyłączone: gra zostaje offline, jak dotąd.',
        'Serwer gry (wiadomości, plamy krwi, duchy)',
        'Serwer gry',
        "Domyślnie The Hunter's Dream. Wystarczy nazwa; porty wybiera gra.",
        'Serwer kooperacji (dzwony i przywołania)',
        'Adres serwera',
        'srv.shadps4.net:31313 to publiczny serwer shadPS4. Dla serwera prywatnego wpisz host:port od osoby, która go prowadzi.',
        'Adres WebAPI',
        'Serwera shadNet, nie serwera gry. Zostaw puste: użyty zostanie adres serwera z portem 31315.',
        'Konto',
        'ID online (NPID)',
        'Nazwa twojego konta shadNet, nie e-mail. Zarejestruj się na shadnet.shadps4.net albo zapytaj właściciela prywatnego serwera.',
        'Hasło',
        'Zapisane na tym PC razem z innymi ustawieniami launchera.',
        'Połączenie',
        'UPnP (automatycznie otwórz port na routerze)',
        'Wyłącz przy Tailscale lub innym VPN.',
        'Wszyscy w sesji potrzebują tej samej wersji gry (1.09) i tego samego serwera. Kody zmieniają grę także innym graczom: wyłączcie je, gdy gracie razem.',
        'Online',
        'Offline',
        'Bloodborne jest w twojej bibliotece Steam. Uruchamia się z ustawieniami zapisanymi w tym launcherze.',
        'Konto online jest wpisane, ale „Graj online” jest wyłączone.\n\nTak: graj online.   Nie: graj offline.',
        'ID online to nazwa konta (NPID) zarejestrowanego na serwerze, a nie adres e-mail.',
        'Nie znaleziono Steam na tym PC (albo nikt się jeszcze nie zalogował).',
        'Serwer gry {0}: dostępny',
        'Serwer {0}: dostępny',
        'Sprawdzanie…',
        'Sprawdź połączenie',
        'Steam musi zostać zamknięty na czas dodawania gry; potem uruchomi się ponownie. Zamknąć Steam teraz?',
        'Steam się nie zamknął. Zamknij go sam i spróbuj ponownie.',
        'Serwer gry {0}: niedostępny ({1})',
        'Serwer {0}: niedostępny ({1})',
        'WebAPI {0}: dostępne',
        'WebAPI {0}: odpowiada, ale to nie jest serwer shadNet',
        'WebAPI {0}: niedostępne ({1})',
        'autor: Super Medo',
        'Dodaj do Steam',
        'Pole WebAPI zawiera adres serwera gry; zostanie pominięte.',
        '„Graj online” jest wyłączone: gra uruchomi się offline.',
        'Nie udało się dodać gry do Steam: {}',
        'Ikony przycisków',
        'PlayStation (oryginalne z gry)',
        'Klawiatura',
        'Ikony Xbox i Switch od Dommo (Nexus Mods); ikony klawiatury pokazują domyślne klawisze. Stosowane przy następnym uruchomieniu.',
        'Menu gestów bez ikon sterowania ruchem',
        'Autor: Dommo (Nexus Mods).',
    ],
    'tr': [
        'Çevrim içi ortak oyun',
        "Mesajlar, kan lekeleri ve hayaletler The Hunter's Dream'den gelir; çanlar ve çağırmalar bir shadNet sunucusundan geçer.",
        'Çevrim içi oyna',
        'Kapalı: oyun eskisi gibi çevrim dışı kalır.',
        'Oyun sunucusu (mesajlar, kan lekeleri, hayaletler)',
        'Oyun sunucusu',
        "Varsayılan olarak The Hunter's Dream. Yalnızca ad yeterli; bağlantı noktalarını oyun seçer.",
        'Ortak oyun sunucusu (çanlar ve çağırmalar)',
        'Sunucu adresi',
        'srv.shadps4.net:31313 herkese açık shadPS4 sunucusudur. Özel bir sunucu için, onu çalıştıran kişiden aldığın host:port bilgisini gir.',
        'WebAPI adresi',
        'Oyun sunucusunun değil, shadNet sunucusunun adresi. Boş bırak: sunucu adresi 31315 bağlantı noktasıyla kullanılır.',
        'Hesap',
        'Çevrim içi kimlik (NPID)',
        'shadNet hesap adın, e-posta adresin değil. shadnet.shadps4.net üzerinden kaydol veya özel sunucunun sahibine sor.',
        'Parola',
        'Diğer başlatıcı ayarlarıyla birlikte bu bilgisayarda saklanır.',
        'Bağlantı',
        'UPnP (yönlendiricide otomatik bağlantı noktası aç)',
        'Tailscale veya başka bir VPN ile kapat.',
        'Oturumdaki herkesin aynı oyun sürümüne (1.09) ve aynı sunucuya ihtiyacı var. Hileler oyunu diğer oyuncular için de değiştirir: birlikte oynarken kapatın.',
        'Çevrim içi',
        'Çevrim dışı',
        'Bloodborne Steam kitaplığında. Bu başlatıcıda kayıtlı ayarlarla açılır.',
        'Bir çevrim içi hesap girilmiş, ancak "Çevrim içi oyna" kapalı.\n\nEvet: çevrim içi oyna.   Hayır: çevrim dışı oyna.',
        'Çevrim içi kimlik, sunucuda kaydettiğin hesap adıdır (NPID), e-posta adresin değil.',
        'Bu bilgisayarda Steam bulunamadı (veya henüz kimse oturum açmadı).',
        'Oyun sunucusu {0}: erişilebilir',
        'Sunucu {0}: erişilebilir',
        'Denetleniyor…',
        'Bağlantıyı sına',
        "Oyun eklenirken Steam'in kapanması gerekiyor; sonra yeniden açılır. Steam şimdi kapatılsın mı?",
        'Steam kapanmadı. Kendin kapatıp yeniden dene.',
        'Oyun sunucusu {0}: erişilemiyor ({1})',
        'Sunucu {0}: erişilemiyor ({1})',
        'WebAPI {0}: erişilebilir',
        'WebAPI {0}: yanıt veriyor ama bir shadNet sunucusu değil',
        'WebAPI {0}: erişilemiyor ({1})',
        'Super Medo tarafından',
        "Steam'e ekle",
        'WebAPI alanında oyun sunucusunun adresi var; yok sayılıyor.',
        '"Çevrim içi oyna" kapalı: oyun çevrim dışı başlar.',
        "Oyun Steam'e eklenemedi: {}",
        'Düğme simgeleri',
        'PlayStation (oyunun kendi simgeleri)',
        'Klavye',
        'Xbox ve Switch simgeleri Dommo’dan (Nexus Mods); klavye simgeleri varsayılan tuşları gösterir. Bir sonraki başlatmada uygulanır.',
        'Hareket kontrolü simgeleri olmadan hareketler menüsü',
        'Dommo’dan (Nexus Mods).',
    ],
    'zh': [
        '在线合作',
        "留言、血迹和幽灵来自 The Hunter's Dream；铃铛和召唤通过 shadNet 服务器进行。",
        '在线游玩',
        '关闭：游戏保持离线，和以前一样。',
        '游戏服务器（留言、血迹、幽灵）',
        '游戏服务器',
        "默认为 The Hunter's Dream。只需填写名称，端口由游戏决定。",
        '合作服务器（铃铛和召唤）',
        '服务器地址',
        'srv.shadps4.net:31313 是 shadPS4 的公共服务器。如使用私人服务器，请填写服务器管理者提供的 host:port。',
        'WebAPI 地址',
        '这是 shadNet 服务器的地址，不是游戏服务器的。留空即可：将使用服务器地址加端口 31315。',
        '账户',
        '在线 ID (NPID)',
        '你的 shadNet 账户名，不是邮箱。可在 shadnet.shadps4.net 注册，或向私人服务器的管理者索取。',
        '密码',
        '与启动器的其他设置一起保存在这台电脑上。',
        '连接',
        'UPnP（自动在路由器上打开端口）',
        '使用 Tailscale 或其他 VPN 时请关闭。',
        '同一场次的所有玩家需要相同的游戏版本 (1.09) 和相同的服务器。作弊也会影响其他玩家的游戏：一起游玩时请关闭。',
        '在线',
        '离线',
        'Bloodborne 已加入你的 Steam 库，会使用此启动器中保存的设置启动。',
        '已填写在线账户，但“在线游玩”未开启。\n\n是：在线游玩。   否：离线游玩。',
        '在线 ID 是你在服务器上注册的账户名 (NPID)，不是邮箱地址。',
        '在这台电脑上找不到 Steam（或者还没有人登录过）。',
        '游戏服务器 {0}：可连接',
        '服务器 {0}：可连接',
        '正在检查…',
        '测试连接',
        '添加游戏时需要关闭 Steam，之后会重新启动。现在关闭 Steam 吗？',
        'Steam 没有关闭。请手动关闭后重试。',
        '游戏服务器 {0}：无法连接 ({1})',
        '服务器 {0}：无法连接 ({1})',
        'WebAPI {0}：可连接',
        'WebAPI {0}：有响应，但不是 shadNet 服务器',
        'WebAPI {0}：无法连接 ({1})',
        '作者：Super Medo',
        '添加到 Steam',
        'WebAPI 栏中填写的是游戏服务器地址，将被忽略。',
        '“在线游玩”未开启：游戏将以离线方式启动。',
        '无法将游戏添加到 Steam：{}',
        '按键图标',
        'PlayStation（游戏原版）',
        '键盘',
        'Xbox 和 Switch 图标由 Dommo 制作（Nexus Mods）；键盘图标显示默认按键。下次启动时生效。',
        '不含体感操作图标的手势菜单',
        '作者：Dommo（Nexus Mods）。',
    ],
    'ja': [
        'オンライン協力プレイ',
        "メッセージ、血痕、幻影は The Hunter's Dream から届きます。鐘と召喚は shadNet サーバーを経由します。",
        'オンラインでプレイ',
        'オフ：これまでどおりオフラインで起動します。',
        'ゲームサーバー（メッセージ、血痕、幻影）',
        'ゲームサーバー',
        "既定は The Hunter's Dream。名前だけで十分で、ポートはゲームが選びます。",
        '協力プレイサーバー（鐘と召喚）',
        'サーバーアドレス',
        'srv.shadps4.net:31313 は shadPS4 の公開サーバーです。プライベートサーバーの場合は、運営者から聞いた host:port を入力してください。',
        'WebAPI アドレス',
        'ゲームサーバーではなく shadNet サーバーのものです。空欄にすると、サーバーアドレスとポート 31315 が使われます。',
        'アカウント',
        'オンライン ID (NPID)',
        'shadNet のアカウント名です（メールアドレスではありません）。shadnet.shadps4.net で登録するか、プライベートサーバーの運営者に頼んでください。',
        'パスワード',
        'ランチャーの他の設定と一緒にこの PC に保存されます。',
        '接続',
        'UPnP（ルーターのポートを自動で開く）',
        'Tailscale などの VPN を使うときはオフにしてください。',
        'セッションの全員が同じゲームバージョン (1.09) と同じサーバーを使う必要があります。チートは他のプレイヤーのゲームにも影響するので、一緒に遊ぶときはオフにしてください。',
        'オンライン',
        'オフライン',
        'Bloodborne を Steam ライブラリに追加しました。このランチャーに保存された設定で起動します。',
        'オンラインアカウントが入力されていますが、「オンラインでプレイ」がオフです。\n\nはい：オンラインでプレイ。   いいえ：オフラインでプレイ。',
        'オンライン ID はサーバーに登録したアカウント名 (NPID) で、メールアドレスではありません。',
        'この PC に Steam が見つかりません（またはまだ誰もサインインしていません）。',
        'ゲームサーバー {0}：接続可能',
        'サーバー {0}：接続可能',
        '確認中…',
        '接続テスト',
        'ゲームを追加する間は Steam を閉じる必要があり、その後また起動します。今すぐ Steam を閉じますか？',
        'Steam が閉じませんでした。手動で閉じてからもう一度お試しください。',
        'ゲームサーバー {0}：接続できません ({1})',
        'サーバー {0}：接続できません ({1})',
        'WebAPI {0}：接続可能',
        'WebAPI {0}：応答はありますが shadNet サーバーではありません',
        'WebAPI {0}：接続できません ({1})',
        '制作：Super Medo',
        'Steam に追加',
        'WebAPI 欄にゲームサーバーのアドレスが入っているため、無視されます。',
        '「オンラインでプレイ」がオフのため、オフラインで起動します。',
        'ゲームを Steam に追加できませんでした: {}',
        'ボタンアイコン',
        'PlayStation（ゲーム本来のもの）',
        'キーボード',
        'Xbox と Switch のアイコンは Dommo 作（Nexus Mods）。キーボードのアイコンは既定のキーを表示します。次回起動時に適用されます。',
        'モーション操作アイコンなしのジェスチャーメニュー',
        'Dommo 作（Nexus Mods）。',
    ],
    'ko': [
        '온라인 협동',
        "메시지, 혈흔, 유령은 The Hunter's Dream에서 오고, 종과 소환은 shadNet 서버를 거칩니다.",
        '온라인으로 플레이',
        '끄면: 게임이 지금처럼 오프라인으로 실행됩니다.',
        '게임 서버 (메시지, 혈흔, 유령)',
        '게임 서버',
        "기본값은 The Hunter's Dream입니다. 이름만 있으면 되고 포트는 게임이 고릅니다.",
        '협동 서버 (종과 소환)',
        '서버 주소',
        'srv.shadps4.net:31313은 shadPS4 공개 서버입니다. 개인 서버라면 운영자에게 받은 host:port를 입력하세요.',
        'WebAPI 주소',
        '게임 서버가 아니라 shadNet 서버의 주소입니다. 비워 두면 서버 주소와 포트 31315가 사용됩니다.',
        '계정',
        '온라인 ID (NPID)',
        '이메일이 아닌 shadNet 계정 이름입니다. shadnet.shadps4.net에서 가입하거나 개인 서버 운영자에게 요청하세요.',
        '비밀번호',
        '다른 런처 설정과 함께 이 PC에 저장됩니다.',
        '연결',
        'UPnP (라우터 포트 자동 열기)',
        'Tailscale이나 다른 VPN을 쓸 때는 끄세요.',
        '세션의 모든 플레이어는 같은 게임 버전(1.09)과 같은 서버를 써야 합니다. 치트는 다른 플레이어의 게임도 바꾸니 함께 플레이할 때는 끄세요.',
        '온라인',
        '오프라인',
        'Bloodborne이 Steam 라이브러리에 추가되었습니다. 이 런처에 저장된 설정으로 실행됩니다.',
        '온라인 계정이 입력되어 있지만 "온라인으로 플레이"가 꺼져 있습니다.\n\n예: 온라인으로 플레이.   아니요: 오프라인으로 플레이.',
        '온라인 ID는 서버에 등록한 계정 이름(NPID)이며 이메일 주소가 아닙니다.',
        '이 PC에서 Steam을 찾을 수 없습니다 (또는 아직 아무도 로그인하지 않았습니다).',
        '게임 서버 {0}: 연결 가능',
        '서버 {0}: 연결 가능',
        '확인 중…',
        '연결 테스트',
        '게임을 추가하는 동안 Steam을 닫아야 하며, 그 후 다시 실행됩니다. 지금 Steam을 닫을까요?',
        'Steam이 닫히지 않았습니다. 직접 닫은 뒤 다시 시도하세요.',
        '게임 서버 {0}: 연결 불가 ({1})',
        '서버 {0}: 연결 불가 ({1})',
        'WebAPI {0}: 연결 가능',
        'WebAPI {0}: 응답은 있지만 shadNet 서버가 아닙니다',
        'WebAPI {0}: 연결 불가 ({1})',
        '제작: Super Medo',
        'Steam에 추가',
        'WebAPI 칸에 게임 서버 주소가 들어 있어 무시됩니다.',
        '"온라인으로 플레이"가 꺼져 있어 오프라인으로 시작합니다.',
        '게임을 Steam에 추가할 수 없습니다: {}',
        '버튼 아이콘',
        'PlayStation (게임 기본)',
        '키보드',
        'Xbox 및 Switch 아이콘 제작: Dommo (Nexus Mods). 키보드 아이콘은 기본 키를 표시합니다. 다음 실행 시 적용됩니다.',
        '모션 컨트롤 아이콘이 없는 제스처 메뉴',
        '제작: Dommo (Nexus Mods).',
    ],
}
