# SPDX-License-Identifier: GPL-2.0-or-later
"""Translations of the Windows launcher. KEYS holds the English texts; every language lists its
texts in the same order. Russian lives next to the English text in bbport_launcher_win.py.
Missing or empty entries fall back to English."""

KEYS = [
    'Play', 'Graphics', 'Display & FPS', 'Game & effects', 'Mods & patches', 'Advanced', 'Log',
    'PLAY', 'Stop', 'native port · Windows', "In the game: Insert or L3+R3\nopens the port's menu.",
    'Ready check', 'Quick settings', 'Frame rate', 'Upscaler', 'Preset', 'Output', 'Fullscreen',
    'CUSA03173 · game version {}', 'Game folder not set', 'Choose your game folder (Game & effects)',
    '✓ Game version {}: every patch available',
    '⚠ Game version {}: runs at 30 FPS without the community patches (they are for 1.09)',
    '✗ No eboot.bin in the game folder (Game & effects)',
    '✓ Saves found in {}', '• No saves yet: the game creates them in {}',
    '✓ Graphics card: {}', '• Graphics card: not checked', '• Checking the graphics card…',
    '✗ No Vulkan 1.3 graphics card found (update the driver)',
    '✓ FSR 4 assets installed', '• FSR 4 assets missing (Graphics); FSR 3.1 is used meanwhile',
    'Choose the game folder first.', 'Preparing the game; it opens in its own window…',
    'The game is running.', 'Restarting with the new settings…',
    '\n— the game exited (code {}) —\n', 'Could not start: {}',
    'Choose the game folder with eboot.bin (CUSA03173).',
    # Graphics
    'Stored in bbport.ini; the in-game menu (Insert or L3+R3) changes the same values.',
    'Upscaling',
    "Temporal upscaling with the game's own motion vectors. FSR 4 needs its assets (below) and a GPU with INT8 dot products; otherwise the game falls back to FSR 3.1 by itself.",
    'Quality preset', 'Render scale per axis: Quality renders at 1/1.5 of the output size.',
    'Output resolution', 'What the upscaler produces; the HUD is drawn at this size too.',
    'Live resolution changes',
    'Off: outputs other than 1080p are set by a patch at start (fastest; changing them in the game restarts it). On: change output and preset in the game without a restart, at a cost.',
    'Sharpening (RCAS)', 'Sharpness', 'Object motion vectors',
    'Less ghosting on characters, cloth and weapons; costs about 10% FPS.',
    'FSR 4 assets', 'Download FSR 4 assets',
    "From FireBurn/Q2RTX on GitHub (built from AMD's MIT-licensed FidelityFX source), about 30 MB, into the fsr4_shaders folder of the port.",
    'Installed: {} files in {}.', '{} of {} files missing in {}.', 'Download failed: {}',
    'Detail', 'Model detail (LOD)', 'A game patch (game version 1.09).', 'Show the FPS counter',
    'FSR 4 (best quality)', 'FSR 4.1.1 (needs fsr4_411 assets)', 'FSR 3.1 (every GPU)',
    'TAA (native resolution anti-aliasing)', 'Off',
    'Auto (by graphics card)', 'Off (faster)', 'On (change without restarting)',
    'As in the game', 'Highest (−2)', 'Lower (1)', 'Lowest (2)',
    # Display
    'Applied when the game starts.',
    'Community patches for game version 1.09. Unlocked makes the game use the real frame time. Other game versions always run at 30 FPS (the patches would corrupt them).',
    'Frame cap (unlocked mode)',
    "Above about 120 FPS the game's movement timing breaks (running and rolling get slower, physics and animations can glitch): higher caps are at your own risk.",
    'Frames ahead of the GPU',
    '1 keeps frame pacing even; more can raise FPS when the graphics card is the limit.',
    'Window', 'Presentation', 'Allow HDR output', 'When HDR is on in Windows and the display supports it.',
    'Unlocked (frame-time patch)', '30 FPS (as on PS4)',
    'Auto: display refresh, max 120 (recommended)', 'No limit',
    'Mailbox (low latency, no tearing)', 'Immediate (tearing)', '1 (default)', 'Unbounded',
    'Your game is version {}: these options are patches for 1.09 and are not applied; the game runs at 30 FPS. Update the dump to 1.09 to use them.',
    # Game
    'Your game dump, saves and the game patches.', 'Game', 'Game folder', 'Choose the folder with eboot.bin',
    'Your own dump of CUSA03173 (eboot.bin, sce_module, sce_sys, dvdroot_ps4); version 1.09 for the community patches.',
    'Saves folder', 'Choose the saves folder', 'Empty: {} (shader caches are kept there too).',
    'Game language', 'Player name', 'Where the game shows the PSN name; empty: the default.',
    'Effects', 'Chromatic aberration', 'Depth of field', 'Motion blur', 'Ambient occlusion (SSAO)',
    "The game's own anti-aliasing", 'Shadows of dynamic lights', 'Screen-space reflections (not in the original)',
    'Extras', 'Skip the intro logos and movie', 'Free camera (hold Cross + L3; keyboard Space + Z)',
    'Game debug menu (left touchpad / Tab; needs the debug fonts)',
    'Effects and extras are game patches for version 1.09, applied at start.',
    'English', 'Russian', 'Japanese', 'French', 'Spanish', 'German', 'Italian',
    # Mods
    'The game files are never changed: mods are layered over them at start.', 'Mods', 'Load mods',
    'Loose-file mods, each in its own folder (with dvdroot_ps4, or chr\\, parts\\ … directly).',
    'Mods folder', 'Choose the mods folder', 'Empty: {}', 'Third-party patches', 'Patches folder',
    'Choose the patches folder', 'shadPS4/GoldHEN XML patch files for version 1.09. Empty: {}',
    'Refresh', 'No mods in {} yet.', 'Lower in the list loads later and wins conflicts.',
    'No patch files for version 1.09 yet.',
    # Advanced
    'Launcher options, performance switches and diagnostics.', 'Launcher', 'Launcher language',
    'Applies when the launcher opens again.', 'Close the launcher when the game starts',
    'Desktop shortcut', 'Port folder', 'Shortcut created on the desktop.', 'Performance',
    'Two-stage GPU pipeline', '20–30% faster; switch it off if the game is unstable.',
    'Auto (8+ threads)', 'On', 'Off (more stable)', 'GPU readbacks',
    'How exactly data the GPU writes is copied back for the game.', 'Relaxed (default)',
    'Diagnostics', 'Frame statistics in the log (every 5 s)', 'GPU time per pass in the log',
    'Vulkan validation layers (needs the Vulkan SDK; much slower)', 'Extra variables',
    'NAME=value pairs separated by spaces (README lists them).', 'System',
    # Log and folders
    'Copy', 'Clear', 'Browse…', 'Open',
    # Cheats
    'Cheats',
    'Game patches for version 1.09, applied at start. Leave them off for a normal play-through.',
    'Gameplay tweaks',
    'Never die (health stops at 1 HP)',
    'Enemies do not see you (unless attacked)',
    'Enemies do not hear you',
    'Rally never fades',
    'Control the targeted enemy (R3; L3 to go back; not with the free camera)',
    'No Rally (hits do not give health back)',
    'Camera further from the character',
    'No camera auto-rotation while moving',
    'Run with less stick tilt (about 70%)',
    'Dark Souls-style ragdoll physics (corpses fly further)',
    'Clear shader cache',
    'If the game only shows a black screen, this usually helps.',
    'Shader cache cleared. The next start stutters for a few minutes while it is rebuilt.',
    # Updates
    'Version {} is available.',
    'Update',
    "What's new",
    'Install version {} now? The launcher closes, installs it and opens again. Saves and settings are kept.',
    'Downloading version {}… {}%',
    'Update failed: {}',
    'Close the game before updating.',
    'Check for updates when the launcher opens',
    'Check for updates',
    'You have the latest version ({}).',
    'Could not check for updates: {}',
    'Could not install the update. Download it from the releases page.',
]

TRANSLATIONS = {
    'ar': [
        'العب', 'الرسومات', 'الشاشة ومعدل الإطارات', 'اللعبة والمؤثرات', 'التعديلات والرقع', 'متقدم', 'السجل',
        'العب', 'إيقاف', 'منفذ أصلي · ويندوز', 'داخل اللعبة: Insert أو L3+R3\nيفتح قائمة المنفذ.',
        'فحص الجاهزية', 'إعدادات سريعة', 'معدل الإطارات', 'أداة التكبير', 'الإعداد المسبق', 'الدقة', 'ملء الشاشة',
        'CUSA03173 · إصدار اللعبة {}', 'لم يتم اختيار مجلد اللعبة', 'اختر مجلد اللعبة (اللعبة والمؤثرات)',
        '✓ إصدار اللعبة {}: كل الرقع متاحة',
        '⚠ إصدار اللعبة {}: تعمل بـ 30 إطارًا بدون رقع المجتمع (مخصصة للإصدار 1.09)',
        '✗ لا يوجد eboot.bin في مجلد اللعبة (اللعبة والمؤثرات)',
        '✓ تم العثور على حفظ في {}', '• لا يوجد حفظ بعد: ستنشئه اللعبة في {}',
        '✓ بطاقة الرسومات: {}', '• بطاقة الرسومات: لم يتم الفحص', '• جارٍ فحص بطاقة الرسومات…',
        '✗ لم يتم العثور على بطاقة رسومات تدعم Vulkan 1.3 (حدّث التعريف)',
        '✓ ملفات FSR 4 مثبتة', '• ملفات FSR 4 غير موجودة (الرسومات)؛ يُستخدم FSR 3.1 مؤقتًا',
        'اختر مجلد اللعبة أولًا.', 'جارٍ تجهيز اللعبة؛ ستفتح في نافذتها الخاصة…',
        'اللعبة تعمل.', 'إعادة التشغيل بالإعدادات الجديدة…',
        '\n— أُغلقت اللعبة (الرمز {}) —\n', 'تعذّر التشغيل: {}',
        'اختر مجلد اللعبة الذي يحتوي eboot.bin (CUSA03173).',
        'محفوظة في bbport.ini؛ قائمة اللعبة (Insert أو L3+R3) تغيّر القيم نفسها.',
        'التكبير',
        'تكبير زمني باستخدام متجهات الحركة الخاصة باللعبة. يحتاج FSR 4 إلى ملفاته (بالأسفل) وبطاقة تدعم INT8؛ وإلا تعود اللعبة تلقائيًا إلى FSR 3.1.',
        'إعداد الجودة', 'مقياس الرسم لكل محور: Quality يرسم بـ 1/1.5 من دقة الإخراج.',
        'دقة الإخراج', 'ما ينتجه المكبّر؛ وتُرسم الواجهة بهذه الدقة أيضًا.',
        'تغيير الدقة أثناء اللعب',
        'إيقاف: الدقات غير 1080p تُضبط برقعة عند التشغيل (الأسرع؛ تغييرها داخل اللعبة يعيد تشغيلها). تشغيل: غيّر الدقة والإعداد داخل اللعبة دون إعادة تشغيل، مع كلفة في الأداء.',
        'الحدة (RCAS)', 'قوة الحدة', 'متجهات حركة الأجسام',
        'تقليل الظلال المتبقية على الشخصيات والملابس والأسلحة؛ تكلّف نحو 10% من الإطارات.',
        'ملفات FSR 4', 'تنزيل ملفات FSR 4',
        'من FireBurn/Q2RTX على GitHub (مبنية من شيفرة AMD FidelityFX المرخصة MIT)، نحو 30 ميغابايت، إلى مجلد fsr4_shaders في المنفذ.',
        'مثبتة: {} ملفًا في {}.', 'ينقص {} من {} ملفًا في {}.', 'فشل التنزيل: {}',
        'التفاصيل', 'تفاصيل النماذج (LOD)', 'رقعة للعبة (الإصدار 1.09).', 'إظهار عدّاد الإطارات',
        'FSR 4 (أفضل جودة)', 'FSR 4.1.1 (يحتاج ملفات fsr4_411)', 'FSR 3.1 (أي بطاقة)',
        'TAA (تنعيم بالدقة الأصلية)', 'إيقاف',
        'تلقائي (حسب البطاقة)', 'إيقاف (أسرع)', 'تشغيل (تغيير دون إعادة تشغيل)',
        'كما في اللعبة', 'الأعلى (−2)', 'أقل (1)', 'الأدنى (2)',
        'تُطبّق عند تشغيل اللعبة.',
        'رقع المجتمع لإصدار اللعبة 1.09. وضع «بدون حد» يجعل اللعبة تستخدم زمن الإطار الحقيقي. الإصدارات الأخرى تعمل دائمًا بـ 30 إطارًا (الرقع ستفسدها).',
        'حد الإطارات (وضع بدون حد)',
        'فوق نحو 120 إطارًا يختل توقيت الحركة في اللعبة (يبطؤ الركض والتدحرج وقد تضطرب الفيزياء والحركات): الحدود الأعلى على مسؤوليتك.',
        'إطارات مسبقة قبل بطاقة الرسومات',
        'القيمة 1 تحافظ على انتظام الإطارات؛ قيمة أكبر قد ترفع الأداء عندما تكون البطاقة هي الحد.',
        'النافذة', 'طريقة العرض', 'السماح بإخراج HDR', 'عند تفعيل HDR في ويندوز ودعم الشاشة له.',
        'بدون حد (رقعة زمن الإطار)', '30 إطارًا (كما في PS4)',
        'تلقائي: تردد الشاشة، بحد أقصى 120 (موصى به)', 'بدون حد',
        'Mailbox (تأخير منخفض، بلا تمزق)', 'Immediate (مع تمزق)', '1 (افتراضي)', 'بلا حد',
        'لعبتك إصدار {}: هذه الخيارات رقع للإصدار 1.09 ولن تُطبّق؛ تعمل اللعبة بـ 30 إطارًا. حدّث نسختك إلى 1.09 لاستخدامها.',
        'نسخة اللعبة والحفظ ورقع اللعبة.', 'اللعبة', 'مجلد اللعبة', 'اختر المجلد الذي يحتوي eboot.bin',
        'نسختك الخاصة من CUSA03173 (eboot.bin و sce_module و sce_sys و dvdroot_ps4)؛ الإصدار 1.09 لرقع المجتمع.',
        'مجلد الحفظ', 'اختر مجلد الحفظ', 'فارغ: {} (يُحفظ فيه أيضًا كاش الشيدر).',
        'لغة اللعبة', 'اسم اللاعب', 'حيث تعرض اللعبة اسم PSN؛ فارغ: الافتراضي.',
        'المؤثرات', 'الانحراف اللوني', 'عمق المجال', 'ضبابية الحركة', 'الإظلال المحيطي (SSAO)',
        'التنعيم الخاص باللعبة', 'ظلال الأضواء المتحركة', 'انعكاسات الشاشة (غير موجودة في الأصل)',
        'إضافات', 'تخطي الشعارات والمقدمة', 'كاميرا حرة (اضغط Cross + L3؛ لوحة المفاتيح Space + Z)',
        'قائمة تصحيح اللعبة (لوحة اللمس اليسرى / Tab؛ تحتاج خطوط التصحيح)',
        'المؤثرات والإضافات رقع للإصدار 1.09 وتُطبّق عند التشغيل.',
        'الإنجليزية', 'الروسية', 'اليابانية', 'الفرنسية', 'الإسبانية', 'الألمانية', 'الإيطالية',
        'ملفات اللعبة لا تتغير أبدًا: التعديلات تُطبّق فوقها عند التشغيل.', 'التعديلات', 'تحميل التعديلات',
        'تعديلات ملفات، كل تعديل في مجلد خاص (مع dvdroot_ps4 أو chr\\ و parts\\ … مباشرة).',
        'مجلد التعديلات', 'اختر مجلد التعديلات', 'فارغ: {}', 'رقع خارجية', 'مجلد الرقع',
        'اختر مجلد الرقع', 'ملفات رقع XML بصيغة shadPS4/GoldHEN للإصدار 1.09. فارغ: {}',
        'تحديث', 'لا توجد تعديلات في {} بعد.', 'الأسفل في القائمة يُحمّل لاحقًا ويتغلب عند التعارض.',
        'لا توجد ملفات رقع للإصدار 1.09 بعد.',
        'إعدادات المشغّل وخيارات الأداء والتشخيص.', 'المشغّل', 'لغة المشغّل',
        'تُطبّق عند فتح المشغّل مرة أخرى.', 'إغلاق المشغّل عند بدء اللعبة',
        'اختصار على سطح المكتب', 'مجلد المنفذ', 'تم إنشاء الاختصار على سطح المكتب.', 'الأداء',
        'خط معالجة GPU بمرحلتين', 'أسرع بنسبة 20–30%؛ أوقفه إذا كانت اللعبة غير مستقرة.',
        'تلقائي (8 أنوية فأكثر)', 'تشغيل', 'إيقاف (أكثر استقرارًا)', 'قراءة بيانات GPU',
        'مدى دقة إعادة البيانات التي تكتبها البطاقة إلى اللعبة.', 'Relaxed (افتراضي)',
        'التشخيص', 'إحصاءات الإطارات في السجل (كل 5 ثوانٍ)', 'زمن GPU لكل مرحلة في السجل',
        'طبقات التحقق Vulkan (تحتاج Vulkan SDK؛ أبطأ بكثير)', 'متغيرات إضافية',
        'أزواج NAME=value مفصولة بمسافات (القائمة في README).', 'لغة النظام',
        'نسخ', 'مسح', 'استعراض…', 'فتح',
        'الغش',
        'رقع للعبة الإصدار 1.09 تُطبّق عند التشغيل. اتركها مطفأة للعب العادي.',
        'تعديلات أسلوب اللعب',
        'لا تموت أبدًا (الصحة لا تنزل عن 1)',
        'الأعداء لا يرونك (ما لم تهاجمهم)',
        'الأعداء لا يسمعونك',
        'استعادة الصحة (Rally) لا تتلاشى',
        'التحكم بالعدو المحدد (R3؛ L3 للعودة؛ ليس مع الكاميرا الحرة)',
        'بدون Rally (الضربات لا تعيد الصحة)',
        'الكاميرا أبعد عن الشخصية',
        'بدون دوران تلقائي للكاميرا أثناء الحركة',
        'الركض بإمالة أقل للعصا (نحو 70%)',
        'فيزياء أجساد مثل Dark Souls (الجثث تطير أبعد)',
        'مسح كاش الشيدر',
        'إذا ظهرت شاشة سوداء فقط، فهذا يساعد عادةً.',
        'تم مسح كاش الشيدر. سيكون التشغيل التالي متقطعًا لبضع دقائق أثناء إعادة بنائه.',
        'الإصدار {} متاح.',
        'تحديث',
        'ما الجديد',
        'تثبيت الإصدار {} الآن؟ سيُغلق المشغّل ويثبّته ثم يفتح من جديد. يبقى الحفظ والإعدادات كما هي.',
        'جارٍ تنزيل الإصدار {}… {}%',
        'فشل التحديث: {}',
        'أغلق اللعبة قبل التحديث.',
        'التحقق من التحديثات عند فتح المشغّل',
        'التحقق من التحديثات',
        'لديك أحدث إصدار ({}).',
        'تعذّر التحقق من التحديثات: {}',
        'تعذّر تثبيت التحديث. نزّله من صفحة الإصدارات.',
    ],
    'es': [
        'Jugar', 'Gráficos', 'Pantalla y FPS', 'Juego y efectos', 'Mods y parches', 'Avanzado', 'Registro',
        'JUGAR', 'Detener', 'port nativo · Windows', 'En el juego: Insert o L3+R3\nabre el menú del port.',
        'Comprobación', 'Ajustes rápidos', 'Velocidad de fotogramas', 'Escalador', 'Preajuste', 'Salida', 'Pantalla completa',
        'CUSA03173 · versión del juego {}', 'Carpeta del juego sin elegir', 'Elige la carpeta del juego (Juego y efectos)',
        '✓ Versión del juego {}: todos los parches disponibles',
        '⚠ Versión del juego {}: funciona a 30 FPS sin los parches de la comunidad (son para la 1.09)',
        '✗ No hay eboot.bin en la carpeta del juego (Juego y efectos)',
        '✓ Partidas guardadas en {}', '• Aún no hay partidas: el juego las creará en {}',
        '✓ Tarjeta gráfica: {}', '• Tarjeta gráfica: sin comprobar', '• Comprobando la tarjeta gráfica…',
        '✗ No se encontró una tarjeta con Vulkan 1.3 (actualiza el controlador)',
        '✓ Archivos de FSR 4 instalados', '• Faltan los archivos de FSR 4 (Gráficos); mientras tanto se usa FSR 3.1',
        'Primero elige la carpeta del juego.', 'Preparando el juego; se abrirá en su propia ventana…',
        'El juego está en marcha.', 'Reiniciando con los nuevos ajustes…',
        '\n— el juego se cerró (código {}) —\n', 'No se pudo iniciar: {}',
        'Elige la carpeta del juego con eboot.bin (CUSA03173).',
        'Se guarda en bbport.ini; el menú del juego (Insert o L3+R3) cambia los mismos valores.',
        'Escalado',
        'Escalado temporal con los vectores de movimiento del propio juego. FSR 4 necesita sus archivos (abajo) y una GPU con INT8; si no, el juego vuelve solo a FSR 3.1.',
        'Preajuste de calidad', 'Escala de render por eje: Quality renderiza a 1/1,5 del tamaño de salida.',
        'Resolución de salida', 'Lo que produce el escalador; la interfaz también se dibuja a este tamaño.',
        'Cambio de resolución en vivo',
        'Desactivado: las salidas distintas de 1080p se fijan con un parche al iniciar (más rápido; cambiarlas en el juego lo reinicia). Activado: cambia salida y preajuste sin reiniciar, con un coste.',
        'Nitidez (RCAS)', 'Intensidad de nitidez', 'Vectores de movimiento de objetos',
        'Menos estelas en personajes, ropa y armas; cuesta alrededor de un 10% de FPS.',
        'Archivos de FSR 4', 'Descargar archivos de FSR 4',
        'Desde FireBurn/Q2RTX en GitHub (compilados del código FidelityFX de AMD con licencia MIT), unos 30 MB, en la carpeta fsr4_shaders del port.',
        'Instalados: {} archivos en {}.', 'Faltan {} de {} archivos en {}.', 'La descarga falló: {}',
        'Detalle', 'Detalle de modelos (LOD)', 'Un parche del juego (versión 1.09).', 'Mostrar el contador de FPS',
        'FSR 4 (mejor calidad)', 'FSR 4.1.1 (necesita archivos fsr4_411)', 'FSR 3.1 (cualquier GPU)',
        'TAA (antialiasing a resolución nativa)', 'Desactivado',
        'Automático (según la tarjeta)', 'Desactivado (más rápido)', 'Activado (cambiar sin reiniciar)',
        'Como en el juego', 'Máximo (−2)', 'Menor (1)', 'Mínimo (2)',
        'Se aplica al iniciar el juego.',
        'Parches de la comunidad para la versión 1.09. Sin límite hace que el juego use el tiempo real de cada fotograma. Otras versiones siempre van a 30 FPS (los parches las dañarían).',
        'Límite de FPS (modo sin límite)',
        'Por encima de unos 120 FPS se rompe el ritmo de movimiento del juego (correr y rodar se vuelven lentos, la física y animaciones pueden fallar): límites mayores bajo tu responsabilidad.',
        'Fotogramas por delante de la GPU',
        '1 mantiene un ritmo de fotogramas uniforme; más puede subir los FPS si la tarjeta es el límite.',
        'Ventana', 'Presentación', 'Permitir salida HDR', 'Cuando HDR está activado en Windows y la pantalla lo admite.',
        'Sin límite (parche de tiempo de fotograma)', '30 FPS (como en PS4)',
        'Automático: frecuencia de la pantalla, máx. 120 (recomendado)', 'Sin límite',
        'Mailbox (baja latencia, sin cortes)', 'Immediate (con cortes)', '1 (predeterminado)', 'Sin límite',
        'Tu juego es la versión {}: estas opciones son parches para la 1.09 y no se aplican; el juego va a 30 FPS. Actualiza el volcado a la 1.09 para usarlas.',
        'Tu volcado del juego, partidas y parches.', 'Juego', 'Carpeta del juego', 'Elige la carpeta con eboot.bin',
        'Tu propio volcado de CUSA03173 (eboot.bin, sce_module, sce_sys, dvdroot_ps4); versión 1.09 para los parches de la comunidad.',
        'Carpeta de partidas', 'Elige la carpeta de partidas', 'Vacío: {} (también guarda la caché de shaders).',
        'Idioma del juego', 'Nombre del jugador', 'Donde el juego muestra el nombre de PSN; vacío: el predeterminado.',
        'Efectos', 'Aberración cromática', 'Profundidad de campo', 'Desenfoque de movimiento', 'Oclusión ambiental (SSAO)',
        'Antialiasing propio del juego', 'Sombras de luces dinámicas', 'Reflejos en pantalla (no estaban en el original)',
        'Extras', 'Saltar logotipos y vídeo de introducción', 'Cámara libre (mantén Cross + L3; teclado Space + Z)',
        'Menú de depuración (touchpad izquierdo / Tab; necesita las fuentes de depuración)',
        'Los efectos y extras son parches para la versión 1.09 y se aplican al iniciar.',
        'Inglés', 'Ruso', 'Japonés', 'Francés', 'Español', 'Alemán', 'Italiano',
        'Los archivos del juego nunca cambian: los mods se superponen al iniciar.', 'Mods', 'Cargar mods',
        'Mods de archivos sueltos, cada uno en su carpeta (con dvdroot_ps4, o chr\\, parts\\ … directamente).',
        'Carpeta de mods', 'Elige la carpeta de mods', 'Vacío: {}', 'Parches de terceros', 'Carpeta de parches',
        'Elige la carpeta de parches', 'Archivos XML de parches shadPS4/GoldHEN para la 1.09. Vacío: {}',
        'Actualizar', 'Aún no hay mods en {}.', 'Más abajo en la lista se carga después y gana en conflictos.',
        'Aún no hay archivos de parches para la 1.09.',
        'Opciones del lanzador, rendimiento y diagnóstico.', 'Lanzador', 'Idioma del lanzador',
        'Se aplica al volver a abrir el lanzador.', 'Cerrar el lanzador al iniciar el juego',
        'Acceso directo en el escritorio', 'Carpeta del port', 'Acceso directo creado en el escritorio.', 'Rendimiento',
        'Canal de GPU en dos etapas', 'Un 20–30% más rápido; desactívalo si el juego es inestable.',
        'Automático (8+ hilos)', 'Activado', 'Desactivado (más estable)', 'Lecturas de la GPU',
        'Con qué precisión se devuelven al juego los datos que escribe la GPU.', 'Relaxed (predeterminado)',
        'Diagnóstico', 'Estadísticas de fotogramas en el registro (cada 5 s)', 'Tiempo de GPU por pasada en el registro',
        'Capas de validación de Vulkan (necesita el Vulkan SDK; mucho más lento)', 'Variables extra',
        'Pares NOMBRE=valor separados por espacios (lista en el README).', 'Sistema',
        'Copiar', 'Borrar', 'Examinar…', 'Abrir',
        'Trucos',
        'Parches del juego para la versión 1.09, aplicados al iniciar. Déjalos desactivados para una partida normal.',
        'Ajustes de juego',
        'No morir nunca (la salud no baja de 1 PS)',
        'Los enemigos no te ven (salvo si atacas)',
        'Los enemigos no te oyen',
        'El Rally no se desvanece',
        'Controlar al enemigo fijado (R3; L3 para volver; no con la cámara libre)',
        'Sin Rally (los golpes no devuelven salud)',
        'Cámara más alejada del personaje',
        'Sin giro automático de la cámara al moverse',
        'Correr con menos inclinación del stick (~70%)',
        'Física de cuerpos al estilo Dark Souls (los cadáveres vuelan más)',
        'Borrar la caché de shaders',
        'Si el juego solo muestra una pantalla negra, esto suele ayudar.',
        'Caché de shaders borrada. El próximo inicio tendrá tirones unos minutos mientras se reconstruye.',
        'La versión {} está disponible.',
        'Actualizar',
        'Novedades',
        '¿Instalar la versión {} ahora? El lanzador se cerrará, la instalará y volverá a abrirse. Se conservan partidas y ajustes.',
        'Descargando la versión {}… {}%',
        'La actualización falló: {}',
        'Cierra el juego antes de actualizar.',
        'Buscar actualizaciones al abrir el lanzador',
        'Buscar actualizaciones',
        'Tienes la última versión ({}).',
        'No se pudieron buscar actualizaciones: {}',
        'No se pudo instalar la actualización. Descárgala desde la página de versiones.',
    ],
    'pt': [
        'Jogar', 'Gráficos', 'Tela e FPS', 'Jogo e efeitos', 'Mods e patches', 'Avançado', 'Registro',
        'JOGAR', 'Parar', 'port nativo · Windows', 'No jogo: Insert ou L3+R3\nabre o menu do port.',
        'Verificação', 'Ajustes rápidos', 'Taxa de quadros', 'Upscaler', 'Predefinição', 'Saída', 'Tela cheia',
        'CUSA03173 · versão do jogo {}', 'Pasta do jogo não definida', 'Escolha a pasta do jogo (Jogo e efeitos)',
        '✓ Versão do jogo {}: todos os patches disponíveis',
        '⚠ Versão do jogo {}: roda a 30 FPS sem os patches da comunidade (são para a 1.09)',
        '✗ Não há eboot.bin na pasta do jogo (Jogo e efeitos)',
        '✓ Saves encontrados em {}', '• Nenhum save ainda: o jogo vai criá-los em {}',
        '✓ Placa de vídeo: {}', '• Placa de vídeo: não verificada', '• Verificando a placa de vídeo…',
        '✗ Nenhuma placa com Vulkan 1.3 encontrada (atualize o driver)',
        '✓ Arquivos do FSR 4 instalados', '• Faltam os arquivos do FSR 4 (Gráficos); por enquanto usa-se FSR 3.1',
        'Escolha a pasta do jogo primeiro.', 'Preparando o jogo; ele abrirá em sua própria janela…',
        'O jogo está rodando.', 'Reiniciando com as novas configurações…',
        '\n— o jogo foi fechado (código {}) —\n', 'Não foi possível iniciar: {}',
        'Escolha a pasta do jogo com eboot.bin (CUSA03173).',
        'Salvo em bbport.ini; o menu do jogo (Insert ou L3+R3) altera os mesmos valores.',
        'Upscaling',
        'Upscaling temporal com os vetores de movimento do próprio jogo. O FSR 4 precisa de seus arquivos (abaixo) e de uma GPU com INT8; senão o jogo volta sozinho para o FSR 3.1.',
        'Predefinição de qualidade', 'Escala de renderização por eixo: Quality renderiza a 1/1,5 da resolução de saída.',
        'Resolução de saída', 'O que o upscaler produz; a interface também é desenhada nesse tamanho.',
        'Troca de resolução ao vivo',
        'Desligado: saídas diferentes de 1080p são definidas por um patch ao iniciar (mais rápido; mudá-las no jogo o reinicia). Ligado: mude saída e predefinição sem reiniciar, com um custo.',
        'Nitidez (RCAS)', 'Intensidade da nitidez', 'Vetores de movimento de objetos',
        'Menos rastros em personagens, roupas e armas; custa cerca de 10% de FPS.',
        'Arquivos do FSR 4', 'Baixar arquivos do FSR 4',
        'Do FireBurn/Q2RTX no GitHub (compilados do código FidelityFX da AMD, licença MIT), cerca de 30 MB, na pasta fsr4_shaders do port.',
        'Instalados: {} arquivos em {}.', 'Faltam {} de {} arquivos em {}.', 'Falha no download: {}',
        'Detalhe', 'Detalhe dos modelos (LOD)', 'Um patch do jogo (versão 1.09).', 'Mostrar o contador de FPS',
        'FSR 4 (melhor qualidade)', 'FSR 4.1.1 (precisa dos arquivos fsr4_411)', 'FSR 3.1 (qualquer GPU)',
        'TAA (anti-aliasing na resolução nativa)', 'Desligado',
        'Automático (pela placa de vídeo)', 'Desligado (mais rápido)', 'Ligado (mudar sem reiniciar)',
        'Como no jogo', 'Máximo (−2)', 'Menor (1)', 'Mínimo (2)',
        'Aplicado ao iniciar o jogo.',
        'Patches da comunidade para a versão 1.09. Sem limite faz o jogo usar o tempo real de cada quadro. Outras versões sempre rodam a 30 FPS (os patches as corromperiam).',
        'Limite de FPS (modo sem limite)',
        'Acima de cerca de 120 FPS o tempo de movimento do jogo quebra (correr e rolar ficam lentos, física e animações podem falhar): limites maiores por sua conta e risco.',
        'Quadros à frente da GPU',
        '1 mantém o ritmo de quadros uniforme; mais pode aumentar o FPS quando a placa é o limite.',
        'Janela', 'Apresentação', 'Permitir saída HDR', 'Quando o HDR está ligado no Windows e a tela suporta.',
        'Sem limite (patch de tempo de quadro)', '30 FPS (como no PS4)',
        'Automático: taxa da tela, máx. 120 (recomendado)', 'Sem limite',
        'Mailbox (baixa latência, sem tearing)', 'Immediate (com tearing)', '1 (padrão)', 'Ilimitado',
        'Seu jogo é a versão {}: estas opções são patches para a 1.09 e não são aplicadas; o jogo roda a 30 FPS. Atualize o dump para a 1.09 para usá-las.',
        'Seu dump do jogo, saves e patches.', 'Jogo', 'Pasta do jogo', 'Escolha a pasta com eboot.bin',
        'Seu próprio dump de CUSA03173 (eboot.bin, sce_module, sce_sys, dvdroot_ps4); versão 1.09 para os patches da comunidade.',
        'Pasta de saves', 'Escolha a pasta de saves', 'Vazio: {} (o cache de shaders também fica lá).',
        'Idioma do jogo', 'Nome do jogador', 'Onde o jogo mostra o nome da PSN; vazio: o padrão.',
        'Efeitos', 'Aberração cromática', 'Profundidade de campo', 'Desfoque de movimento', 'Oclusão de ambiente (SSAO)',
        'Anti-aliasing do próprio jogo', 'Sombras de luzes dinâmicas', 'Reflexos de tela (não existiam no original)',
        'Extras', 'Pular logos e vídeo de abertura', 'Câmera livre (segure Cross + L3; teclado Space + Z)',
        'Menu de depuração (touchpad esquerdo / Tab; precisa das fontes de depuração)',
        'Efeitos e extras são patches para a versão 1.09, aplicados ao iniciar.',
        'Inglês', 'Russo', 'Japonês', 'Francês', 'Espanhol', 'Alemão', 'Italiano',
        'Os arquivos do jogo nunca mudam: os mods são sobrepostos ao iniciar.', 'Mods', 'Carregar mods',
        'Mods de arquivos soltos, cada um em sua pasta (com dvdroot_ps4, ou chr\\, parts\\ … diretamente).',
        'Pasta de mods', 'Escolha a pasta de mods', 'Vazio: {}', 'Patches de terceiros', 'Pasta de patches',
        'Escolha a pasta de patches', 'Arquivos XML de patches shadPS4/GoldHEN para a 1.09. Vazio: {}',
        'Atualizar', 'Ainda não há mods em {}.', 'Mais abaixo na lista carrega depois e vence conflitos.',
        'Ainda não há arquivos de patches para a 1.09.',
        'Opções do launcher, desempenho e diagnóstico.', 'Launcher', 'Idioma do launcher',
        'Aplica-se ao reabrir o launcher.', 'Fechar o launcher ao iniciar o jogo',
        'Atalho na área de trabalho', 'Pasta do port', 'Atalho criado na área de trabalho.', 'Desempenho',
        'Pipeline de GPU em dois estágios', '20–30% mais rápido; desligue se o jogo ficar instável.',
        'Automático (8+ threads)', 'Ligado', 'Desligado (mais estável)', 'Leituras da GPU',
        'Com que precisão os dados escritos pela GPU voltam para o jogo.', 'Relaxed (padrão)',
        'Diagnóstico', 'Estatísticas de quadros no registro (a cada 5 s)', 'Tempo de GPU por passe no registro',
        'Camadas de validação do Vulkan (precisa do Vulkan SDK; muito mais lento)', 'Variáveis extras',
        'Pares NOME=valor separados por espaços (lista no README).', 'Sistema',
        'Copiar', 'Limpar', 'Procurar…', 'Abrir',
        'Trapaças',
        'Patches do jogo para a versão 1.09, aplicados ao iniciar. Deixe desligados para uma partida normal.',
        'Ajustes de jogabilidade',
        'Nunca morrer (a vida não cai abaixo de 1 PV)',
        'Inimigos não te veem (a menos que atacados)',
        'Inimigos não te ouvem',
        'O Rally nunca some',
        'Controlar o inimigo travado (R3; L3 para voltar; não com a câmera livre)',
        'Sem Rally (golpes não devolvem vida)',
        'Câmera mais longe do personagem',
        'Sem rotação automática da câmera ao andar',
        'Correr com menos inclinação do analógico (~70%)',
        'Física de corpos estilo Dark Souls (corpos voam mais longe)',
        'Limpar o cache de shaders',
        'Se o jogo mostrar só uma tela preta, isso costuma resolver.',
        'Cache de shaders limpo. O próximo início terá travadas por alguns minutos enquanto ele é refeito.',
        'A versão {} está disponível.',
        'Atualizar',
        'Novidades',
        'Instalar a versão {} agora? O launcher fecha, instala e abre de novo. Saves e configurações são mantidos.',
        'Baixando a versão {}… {}%',
        'Falha na atualização: {}',
        'Feche o jogo antes de atualizar.',
        'Procurar atualizações ao abrir o launcher',
        'Procurar atualizações',
        'Você tem a versão mais recente ({}).',
        'Não foi possível procurar atualizações: {}',
        'Não foi possível instalar a atualização. Baixe-a na página de versões.',
    ],
    'fr': [
        'Jouer', 'Graphismes', 'Affichage et FPS', 'Jeu et effets', 'Mods et patchs', 'Avancé', 'Journal',
        'JOUER', 'Arrêter', 'portage natif · Windows', 'En jeu : Insert ou L3+R3\nouvre le menu du portage.',
        'Vérification', 'Réglages rapides', 'Fréquence d’images', 'Upscaler', 'Préréglage', 'Sortie', 'Plein écran',
        'CUSA03173 · version du jeu {}', 'Dossier du jeu non défini', 'Choisissez le dossier du jeu (Jeu et effets)',
        '✓ Version du jeu {} : tous les patchs disponibles',
        '⚠ Version du jeu {} : tourne à 30 FPS sans les patchs de la communauté (prévus pour la 1.09)',
        '✗ Pas de eboot.bin dans le dossier du jeu (Jeu et effets)',
        '✓ Sauvegardes trouvées dans {}', '• Pas encore de sauvegarde : le jeu les créera dans {}',
        '✓ Carte graphique : {}', '• Carte graphique : non vérifiée', '• Vérification de la carte graphique…',
        '✗ Aucune carte Vulkan 1.3 trouvée (mettez à jour le pilote)',
        '✓ Fichiers FSR 4 installés', '• Fichiers FSR 4 manquants (Graphismes) ; FSR 3.1 est utilisé en attendant',
        'Choisissez d’abord le dossier du jeu.', 'Préparation du jeu ; il s’ouvrira dans sa propre fenêtre…',
        'Le jeu est lancé.', 'Redémarrage avec les nouveaux réglages…',
        '\n— le jeu s’est fermé (code {}) —\n', 'Impossible de lancer : {}',
        'Choisissez le dossier du jeu contenant eboot.bin (CUSA03173).',
        'Enregistré dans bbport.ini ; le menu en jeu (Insert ou L3+R3) modifie les mêmes valeurs.',
        'Upscaling',
        'Upscaling temporel avec les vecteurs de mouvement du jeu. FSR 4 nécessite ses fichiers (ci-dessous) et un GPU avec INT8 ; sinon le jeu repasse seul à FSR 3.1.',
        'Préréglage de qualité', 'Échelle de rendu par axe : Quality rend à 1/1,5 de la taille de sortie.',
        'Résolution de sortie', 'Ce que produit l’upscaler ; l’interface est aussi dessinée à cette taille.',
        'Changement de résolution en direct',
        'Désactivé : les sorties autres que 1080p sont fixées par un patch au lancement (le plus rapide ; les changer en jeu le relance). Activé : changez sortie et préréglage sans relancer, avec un coût.',
        'Netteté (RCAS)', 'Intensité de la netteté', 'Vecteurs de mouvement des objets',
        'Moins de traînées sur les personnages, vêtements et armes ; coûte environ 10 % de FPS.',
        'Fichiers FSR 4', 'Télécharger les fichiers FSR 4',
        'Depuis FireBurn/Q2RTX sur GitHub (compilés à partir du code FidelityFX d’AMD sous licence MIT), environ 30 Mo, dans le dossier fsr4_shaders du portage.',
        'Installés : {} fichiers dans {}.', '{} fichiers sur {} manquants dans {}.', 'Échec du téléchargement : {}',
        'Détails', 'Détail des modèles (LOD)', 'Un patch du jeu (version 1.09).', 'Afficher le compteur de FPS',
        'FSR 4 (meilleure qualité)', 'FSR 4.1.1 (fichiers fsr4_411 requis)', 'FSR 3.1 (tout GPU)',
        'TAA (anticrénelage en résolution native)', 'Désactivé',
        'Auto (selon la carte)', 'Désactivé (plus rapide)', 'Activé (changer sans relancer)',
        'Comme dans le jeu', 'Maximal (−2)', 'Inférieur (1)', 'Minimal (2)',
        'Appliqué au lancement du jeu.',
        'Patchs de la communauté pour la version 1.09. Illimité fait utiliser au jeu le vrai temps d’image. Les autres versions tournent toujours à 30 FPS (les patchs les corrompraient).',
        'Limite de FPS (mode illimité)',
        'Au-delà d’environ 120 FPS le timing des mouvements du jeu se dérègle (course et roulades ralentissent, physique et animations peuvent bugger) : les limites plus hautes sont à vos risques.',
        'Images d’avance sur le GPU',
        '1 garde un rythme d’images régulier ; plus peut augmenter les FPS quand la carte est la limite.',
        'Fenêtre', 'Présentation', 'Autoriser la sortie HDR', 'Quand le HDR est activé dans Windows et pris en charge par l’écran.',
        'Illimité (patch de temps d’image)', '30 FPS (comme sur PS4)',
        'Auto : fréquence de l’écran, 120 max (recommandé)', 'Aucune limite',
        'Mailbox (faible latence, sans déchirement)', 'Immediate (déchirement)', '1 (par défaut)', 'Illimité',
        'Votre jeu est en version {} : ces options sont des patchs pour la 1.09 et ne sont pas appliquées ; le jeu tourne à 30 FPS. Mettez votre dump à jour en 1.09 pour les utiliser.',
        'Votre dump du jeu, vos sauvegardes et les patchs.', 'Jeu', 'Dossier du jeu', 'Choisissez le dossier contenant eboot.bin',
        'Votre propre dump de CUSA03173 (eboot.bin, sce_module, sce_sys, dvdroot_ps4) ; version 1.09 pour les patchs de la communauté.',
        'Dossier des sauvegardes', 'Choisissez le dossier des sauvegardes', 'Vide : {} (le cache des shaders y est aussi).',
        'Langue du jeu', 'Nom du joueur', 'Là où le jeu affiche le nom PSN ; vide : par défaut.',
        'Effets', 'Aberration chromatique', 'Profondeur de champ', 'Flou de mouvement', 'Occlusion ambiante (SSAO)',
        'Anticrénelage propre au jeu', 'Ombres des lumières dynamiques', 'Réflexions en espace écran (absentes de l’original)',
        'Extras', 'Passer les logos et la vidéo d’intro', 'Caméra libre (maintenir Cross + L3 ; clavier Space + Z)',
        'Menu de débogage (touchpad gauche / Tab ; polices de débogage requises)',
        'Les effets et extras sont des patchs pour la version 1.09, appliqués au lancement.',
        'Anglais', 'Russe', 'Japonais', 'Français', 'Espagnol', 'Allemand', 'Italien',
        'Les fichiers du jeu ne sont jamais modifiés : les mods s’y superposent au lancement.', 'Mods', 'Charger les mods',
        'Mods en fichiers, chacun dans son dossier (avec dvdroot_ps4, ou chr\\, parts\\ … directement).',
        'Dossier des mods', 'Choisissez le dossier des mods', 'Vide : {}', 'Patchs tiers', 'Dossier des patchs',
        'Choisissez le dossier des patchs', 'Fichiers XML de patchs shadPS4/GoldHEN pour la 1.09. Vide : {}',
        'Actualiser', 'Pas encore de mods dans {}.', 'Plus bas dans la liste = chargé après, l’emporte en cas de conflit.',
        'Pas encore de fichiers de patchs pour la 1.09.',
        'Options du lanceur, performances et diagnostic.', 'Lanceur', 'Langue du lanceur',
        'S’applique à la prochaine ouverture du lanceur.', 'Fermer le lanceur au démarrage du jeu',
        'Raccourci sur le bureau', 'Dossier du portage', 'Raccourci créé sur le bureau.', 'Performances',
        'Pipeline GPU en deux étapes', '20 à 30 % plus rapide ; désactivez-le si le jeu est instable.',
        'Auto (8 threads ou plus)', 'Activé', 'Désactivé (plus stable)', 'Relectures GPU',
        'Précision du retour au jeu des données écrites par le GPU.', 'Relaxed (par défaut)',
        'Diagnostic', 'Statistiques d’images dans le journal (toutes les 5 s)', 'Temps GPU par passe dans le journal',
        'Couches de validation Vulkan (Vulkan SDK requis ; bien plus lent)', 'Variables supplémentaires',
        'Paires NOM=valeur séparées par des espaces (liste dans le README).', 'Système',
        'Copier', 'Effacer', 'Parcourir…', 'Ouvrir',
        'Triches',
        'Patchs du jeu pour la version 1.09, appliqués au lancement. Laissez-les désactivés pour une partie normale.',
        'Ajustements de gameplay',
        'Ne jamais mourir (la santé reste à 1 PV minimum)',
        'Les ennemis ne vous voient pas (sauf attaqués)',
        'Les ennemis ne vous entendent pas',
        'Le regain ne s’estompe jamais',
        'Contrôler l’ennemi ciblé (R3 ; L3 pour revenir ; pas avec la caméra libre)',
        'Sans regain (les coups ne rendent pas de santé)',
        'Caméra plus éloignée du personnage',
        'Pas de rotation automatique de la caméra en marchant',
        'Courir avec moins d’inclinaison du stick (~70 %)',
        'Physique des corps façon Dark Souls (les cadavres volent plus loin)',
        'Vider le cache des shaders',
        'Si le jeu n’affiche qu’un écran noir, cela aide généralement.',
        'Cache des shaders vidé. Le prochain lancement saccadera quelques minutes le temps de le reconstruire.',
        'La version {} est disponible.',
        'Mettre à jour',
        'Nouveautés',
        'Installer la version {} maintenant ? Le lanceur se ferme, l’installe et se rouvre. Sauvegardes et réglages sont conservés.',
        'Téléchargement de la version {}… {} %',
        'Échec de la mise à jour : {}',
        'Fermez le jeu avant de mettre à jour.',
        'Rechercher les mises à jour à l’ouverture du lanceur',
        'Rechercher les mises à jour',
        'Vous avez la dernière version ({}).',
        'Impossible de rechercher les mises à jour : {}',
        'Impossible d’installer la mise à jour. Téléchargez-la depuis la page des versions.',
    ],
    'de': [
        'Spielen', 'Grafik', 'Anzeige & FPS', 'Spiel & Effekte', 'Mods & Patches', 'Erweitert', 'Protokoll',
        'SPIELEN', 'Beenden', 'nativer Port · Windows', 'Im Spiel: Einfg oder L3+R3\nöffnet das Port-Menü.',
        'Bereitschaft', 'Schnelleinstellungen', 'Bildrate', 'Upscaler', 'Voreinstellung', 'Ausgabe', 'Vollbild',
        'CUSA03173 · Spielversion {}', 'Spielordner nicht gewählt', 'Spielordner wählen (Spiel & Effekte)',
        '✓ Spielversion {}: alle Patches verfügbar',
        '⚠ Spielversion {}: läuft mit 30 FPS ohne die Community-Patches (sie sind für 1.09)',
        '✗ Kein eboot.bin im Spielordner (Spiel & Effekte)',
        '✓ Spielstände gefunden in {}', '• Noch keine Spielstände: das Spiel legt sie an in {}',
        '✓ Grafikkarte: {}', '• Grafikkarte: nicht geprüft', '• Grafikkarte wird geprüft…',
        '✗ Keine Grafikkarte mit Vulkan 1.3 gefunden (Treiber aktualisieren)',
        '✓ FSR-4-Dateien installiert', '• FSR-4-Dateien fehlen (Grafik); solange wird FSR 3.1 verwendet',
        'Zuerst den Spielordner wählen.', 'Spiel wird vorbereitet; es öffnet sich in einem eigenen Fenster…',
        'Das Spiel läuft.', 'Neustart mit den neuen Einstellungen…',
        '\n— das Spiel wurde beendet (Code {}) —\n', 'Start fehlgeschlagen: {}',
        'Spielordner mit eboot.bin wählen (CUSA03173).',
        'Gespeichert in bbport.ini; das Menü im Spiel (Einfg oder L3+R3) ändert dieselben Werte.',
        'Hochskalierung',
        'Temporale Hochskalierung mit den Bewegungsvektoren des Spiels. FSR 4 braucht seine Dateien (unten) und eine GPU mit INT8; sonst wechselt das Spiel selbst zu FSR 3.1.',
        'Qualitätsstufe', 'Renderauflösung je Achse: Quality rendert mit 1/1,5 der Ausgabegröße.',
        'Ausgabeauflösung', 'Was der Upscaler erzeugt; die Oberfläche wird ebenfalls in dieser Größe gezeichnet.',
        'Auflösung live ändern',
        'Aus: Ausgaben außer 1080p werden beim Start per Patch gesetzt (am schnellsten; Ändern im Spiel startet es neu). An: Ausgabe und Stufe im Spiel ohne Neustart ändern, kostet Leistung.',
        'Schärfen (RCAS)', 'Schärfestärke', 'Bewegungsvektoren von Objekten',
        'Weniger Nachziehen bei Figuren, Kleidung und Waffen; kostet etwa 10 % FPS.',
        'FSR-4-Dateien', 'FSR-4-Dateien herunterladen',
        'Von FireBurn/Q2RTX auf GitHub (aus AMDs MIT-lizenziertem FidelityFX-Quellcode gebaut), etwa 30 MB, in den Ordner fsr4_shaders des Ports.',
        'Installiert: {} Dateien in {}.', '{} von {} Dateien fehlen in {}.', 'Download fehlgeschlagen: {}',
        'Details', 'Modelldetail (LOD)', 'Ein Spiel-Patch (Version 1.09).', 'FPS-Zähler anzeigen',
        'FSR 4 (beste Qualität)', 'FSR 4.1.1 (braucht fsr4_411-Dateien)', 'FSR 3.1 (jede GPU)',
        'TAA (Kantenglättung in nativer Auflösung)', 'Aus',
        'Automatisch (nach Grafikkarte)', 'Aus (schneller)', 'An (ohne Neustart ändern)',
        'Wie im Spiel', 'Höchste (−2)', 'Niedriger (1)', 'Niedrigste (2)',
        'Gilt beim Start des Spiels.',
        'Community-Patches für Spielversion 1.09. Unbegrenzt lässt das Spiel die echte Bildzeit verwenden. Andere Versionen laufen immer mit 30 FPS (die Patches würden sie beschädigen).',
        'FPS-Grenze (unbegrenzter Modus)',
        'Über etwa 120 FPS gerät das Bewegungstiming des Spiels durcheinander (Laufen und Rollen werden langsamer, Physik und Animationen können fehlerhaft sein): höhere Grenzen auf eigenes Risiko.',
        'Bilder vor der GPU',
        '1 hält die Bildausgabe gleichmäßig; mehr kann die FPS erhöhen, wenn die Grafikkarte begrenzt.',
        'Fenster', 'Darstellung', 'HDR-Ausgabe erlauben', 'Wenn HDR in Windows aktiv ist und der Bildschirm es unterstützt.',
        'Unbegrenzt (Bildzeit-Patch)', '30 FPS (wie auf PS4)',
        'Automatisch: Bildwiederholrate, max. 120 (empfohlen)', 'Keine Grenze',
        'Mailbox (geringe Latenz, ohne Tearing)', 'Immediate (mit Tearing)', '1 (Standard)', 'Unbegrenzt',
        'Dein Spiel ist Version {}: diese Optionen sind Patches für 1.09 und werden nicht angewendet; das Spiel läuft mit 30 FPS. Aktualisiere den Dump auf 1.09, um sie zu nutzen.',
        'Dein Spiel-Dump, Spielstände und Spiel-Patches.', 'Spiel', 'Spielordner', 'Ordner mit eboot.bin wählen',
        'Dein eigener Dump von CUSA03173 (eboot.bin, sce_module, sce_sys, dvdroot_ps4); Version 1.09 für die Community-Patches.',
        'Spielstandordner', 'Spielstandordner wählen', 'Leer: {} (dort liegt auch der Shader-Cache).',
        'Spielsprache', 'Spielername', 'Wo das Spiel den PSN-Namen zeigt; leer: Standard.',
        'Effekte', 'Chromatische Aberration', 'Tiefenschärfe', 'Bewegungsunschärfe', 'Umgebungsverdeckung (SSAO)',
        'Eigene Kantenglättung des Spiels', 'Schatten dynamischer Lichter', 'Bildschirmspiegelungen (nicht im Original)',
        'Extras', 'Intro-Logos und -Video überspringen', 'Freie Kamera (Cross + L3 halten; Tastatur Space + Z)',
        'Debug-Menü des Spiels (linkes Touchpad / Tab; braucht die Debug-Schriften)',
        'Effekte und Extras sind Spiel-Patches für Version 1.09 und gelten beim Start.',
        'Englisch', 'Russisch', 'Japanisch', 'Französisch', 'Spanisch', 'Deutsch', 'Italienisch',
        'Die Spieldateien werden nie verändert: Mods werden beim Start darübergelegt.', 'Mods', 'Mods laden',
        'Datei-Mods, jeder in eigenem Ordner (mit dvdroot_ps4, oder chr\\, parts\\ … direkt).',
        'Mod-Ordner', 'Mod-Ordner wählen', 'Leer: {}', 'Patches von Drittanbietern', 'Patch-Ordner',
        'Patch-Ordner wählen', 'shadPS4/GoldHEN-XML-Patchdateien für 1.09. Leer: {}',
        'Aktualisieren', 'Noch keine Mods in {}.', 'Weiter unten in der Liste lädt später und gewinnt bei Konflikten.',
        'Noch keine Patchdateien für 1.09.',
        'Launcher-Optionen, Leistung und Diagnose.', 'Launcher', 'Launcher-Sprache',
        'Gilt beim nächsten Öffnen des Launchers.', 'Launcher beim Spielstart schließen',
        'Desktop-Verknüpfung', 'Port-Ordner', 'Verknüpfung auf dem Desktop erstellt.', 'Leistung',
        'Zweistufige GPU-Pipeline', '20–30 % schneller; abschalten, wenn das Spiel instabil ist.',
        'Automatisch (8+ Threads)', 'An', 'Aus (stabiler)', 'GPU-Rücklesen',
        'Wie genau von der GPU geschriebene Daten ans Spiel zurückgehen.', 'Relaxed (Standard)',
        'Diagnose', 'Bildstatistik im Protokoll (alle 5 s)', 'GPU-Zeit je Durchgang im Protokoll',
        'Vulkan-Validierungsschichten (braucht das Vulkan SDK; viel langsamer)', 'Zusätzliche Variablen',
        'NAME=Wert-Paare durch Leerzeichen getrennt (Liste im README).', 'System',
        'Kopieren', 'Leeren', 'Durchsuchen…', 'Öffnen',
        'Cheats',
        'Spiel-Patches für Version 1.09, beim Start angewendet. Für einen normalen Durchgang ausgeschaltet lassen.',
        'Spielmechanik',
        'Niemals sterben (Gesundheit bleibt bei mindestens 1 LP)',
        'Gegner sehen dich nicht (außer bei Angriff)',
        'Gegner hören dich nicht',
        'Rally verfällt nie',
        'Anvisierten Gegner steuern (R3; L3 zurück; nicht mit freier Kamera)',
        'Kein Rally (Treffer geben keine Gesundheit zurück)',
        'Kamera weiter weg von der Figur',
        'Keine automatische Kameradrehung beim Laufen',
        'Rennen mit weniger Stickneigung (ca. 70 %)',
        'Ragdoll-Physik wie in Dark Souls (Leichen fliegen weiter)',
        'Shader-Cache leeren',
        'Wenn das Spiel nur einen schwarzen Bildschirm zeigt, hilft das meistens.',
        'Shader-Cache geleert. Der nächste Start ruckelt einige Minuten, während er neu aufgebaut wird.',
        'Version {} ist verfügbar.',
        'Aktualisieren',
        'Neuerungen',
        'Version {} jetzt installieren? Der Launcher schließt sich, installiert sie und öffnet sich wieder. Spielstände und Einstellungen bleiben erhalten.',
        'Version {} wird heruntergeladen… {} %',
        'Update fehlgeschlagen: {}',
        'Beende das Spiel vor dem Update.',
        'Beim Öffnen des Launchers nach Updates suchen',
        'Nach Updates suchen',
        'Du hast die neueste Version ({}).',
        'Suche nach Updates fehlgeschlagen: {}',
        'Das Update konnte nicht installiert werden. Lade es von der Release-Seite herunter.',
    ],
    'it': [
        'Gioca', 'Grafica', 'Schermo e FPS', 'Gioco ed effetti', 'Mod e patch', 'Avanzate', 'Registro',
        'GIOCA', 'Ferma', 'port nativo · Windows', 'Nel gioco: Ins o L3+R3\napre il menu del port.',
        'Verifica', 'Impostazioni rapide', 'Frequenza fotogrammi', 'Upscaler', 'Preset', 'Uscita', 'Schermo intero',
        'CUSA03173 · versione del gioco {}', 'Cartella del gioco non impostata', 'Scegli la cartella del gioco (Gioco ed effetti)',
        '✓ Versione del gioco {}: tutte le patch disponibili',
        '⚠ Versione del gioco {}: gira a 30 FPS senza le patch della community (sono per la 1.09)',
        '✗ Nessun eboot.bin nella cartella del gioco (Gioco ed effetti)',
        '✓ Salvataggi trovati in {}', '• Ancora nessun salvataggio: il gioco li creerà in {}',
        '✓ Scheda video: {}', '• Scheda video: non verificata', '• Verifica della scheda video…',
        '✗ Nessuna scheda con Vulkan 1.3 trovata (aggiorna il driver)',
        '✓ File di FSR 4 installati', '• Mancano i file di FSR 4 (Grafica); nel frattempo si usa FSR 3.1',
        'Scegli prima la cartella del gioco.', 'Preparazione del gioco; si aprirà nella sua finestra…',
        'Il gioco è in esecuzione.', 'Riavvio con le nuove impostazioni…',
        '\n— il gioco è stato chiuso (codice {}) —\n', 'Impossibile avviare: {}',
        'Scegli la cartella del gioco con eboot.bin (CUSA03173).',
        'Salvato in bbport.ini; il menu nel gioco (Ins o L3+R3) modifica gli stessi valori.',
        'Upscaling',
        'Upscaling temporale con i vettori di movimento del gioco. FSR 4 richiede i suoi file (sotto) e una GPU con INT8; altrimenti il gioco torna da solo a FSR 3.1.',
        'Preset di qualità', 'Scala di rendering per asse: Quality renderizza a 1/1,5 della risoluzione di uscita.',
        'Risoluzione di uscita', 'Ciò che produce l’upscaler; anche l’interfaccia è disegnata a questa dimensione.',
        'Cambio risoluzione dal vivo',
        'Disattivo: le uscite diverse da 1080p sono impostate da una patch all’avvio (più veloce; cambiarle nel gioco lo riavvia). Attivo: cambia uscita e preset senza riavviare, con un costo.',
        'Nitidezza (RCAS)', 'Intensità della nitidezza', 'Vettori di movimento degli oggetti',
        'Meno scie su personaggi, abiti e armi; costa circa il 10% di FPS.',
        'File di FSR 4', 'Scarica i file di FSR 4',
        'Da FireBurn/Q2RTX su GitHub (compilati dal codice FidelityFX di AMD con licenza MIT), circa 30 MB, nella cartella fsr4_shaders del port.',
        'Installati: {} file in {}.', 'Mancano {} file su {} in {}.', 'Download non riuscito: {}',
        'Dettaglio', 'Dettaglio modelli (LOD)', 'Una patch del gioco (versione 1.09).', 'Mostra il contatore FPS',
        'FSR 4 (qualità migliore)', 'FSR 4.1.1 (richiede i file fsr4_411)', 'FSR 3.1 (qualsiasi GPU)',
        'TAA (antialiasing a risoluzione nativa)', 'Disattivo',
        'Automatico (in base alla scheda)', 'Disattivo (più veloce)', 'Attivo (cambia senza riavviare)',
        'Come nel gioco', 'Massimo (−2)', 'Inferiore (1)', 'Minimo (2)',
        'Applicato all’avvio del gioco.',
        'Patch della community per la versione 1.09. Senza limite fa usare al gioco il tempo reale di ogni fotogramma. Le altre versioni girano sempre a 30 FPS (le patch le corromperebbero).',
        'Limite FPS (modalità senza limite)',
        'Oltre circa 120 FPS la temporizzazione dei movimenti del gioco si rompe (corsa e capriole rallentano, fisica e animazioni possono sbagliare): limiti più alti a tuo rischio.',
        'Fotogrammi in anticipo sulla GPU',
        '1 mantiene uniforme il ritmo dei fotogrammi; di più può alzare gli FPS se la scheda è il limite.',
        'Finestra', 'Presentazione', 'Consenti l’uscita HDR', 'Quando l’HDR è attivo in Windows e lo schermo lo supporta.',
        'Senza limite (patch del tempo di fotogramma)', '30 FPS (come su PS4)',
        'Automatico: frequenza dello schermo, max 120 (consigliato)', 'Nessun limite',
        'Mailbox (bassa latenza, senza tearing)', 'Immediate (con tearing)', '1 (predefinito)', 'Illimitato',
        'Il tuo gioco è la versione {}: queste opzioni sono patch per la 1.09 e non vengono applicate; il gioco gira a 30 FPS. Aggiorna il dump alla 1.09 per usarle.',
        'Il tuo dump del gioco, i salvataggi e le patch.', 'Gioco', 'Cartella del gioco', 'Scegli la cartella con eboot.bin',
        'Il tuo dump di CUSA03173 (eboot.bin, sce_module, sce_sys, dvdroot_ps4); versione 1.09 per le patch della community.',
        'Cartella dei salvataggi', 'Scegli la cartella dei salvataggi', 'Vuoto: {} (contiene anche la cache degli shader).',
        'Lingua del gioco', 'Nome del giocatore', 'Dove il gioco mostra il nome PSN; vuoto: quello predefinito.',
        'Effetti', 'Aberrazione cromatica', 'Profondità di campo', 'Sfocatura di movimento', 'Occlusione ambientale (SSAO)',
        'Antialiasing del gioco', 'Ombre delle luci dinamiche', 'Riflessi in screen space (non nell’originale)',
        'Extra', 'Salta loghi e video introduttivi', 'Telecamera libera (tieni Cross + L3; tastiera Space + Z)',
        'Menu di debug del gioco (touchpad sinistro / Tab; servono i font di debug)',
        'Effetti ed extra sono patch del gioco per la versione 1.09, applicate all’avvio.',
        'Inglese', 'Russo', 'Giapponese', 'Francese', 'Spagnolo', 'Tedesco', 'Italiano',
        'I file del gioco non vengono mai modificati: le mod si sovrappongono all’avvio.', 'Mod', 'Carica le mod',
        'Mod a file sciolti, ognuna nella sua cartella (con dvdroot_ps4, o chr\\, parts\\ … direttamente).',
        'Cartella delle mod', 'Scegli la cartella delle mod', 'Vuoto: {}', 'Patch di terze parti', 'Cartella delle patch',
        'Scegli la cartella delle patch', 'File XML di patch shadPS4/GoldHEN per la 1.09. Vuoto: {}',
        'Aggiorna', 'Ancora nessuna mod in {}.', 'Più in basso nella lista si carica dopo e vince i conflitti.',
        'Ancora nessun file di patch per la 1.09.',
        'Opzioni del launcher, prestazioni e diagnostica.', 'Launcher', 'Lingua del launcher',
        'Si applica alla prossima apertura del launcher.', 'Chiudi il launcher all’avvio del gioco',
        'Collegamento sul desktop', 'Cartella del port', 'Collegamento creato sul desktop.', 'Prestazioni',
        'Pipeline GPU a due stadi', 'Più veloce del 20–30%; disattivala se il gioco è instabile.',
        'Automatico (8+ thread)', 'Attivo', 'Disattivo (più stabile)', 'Riletture della GPU',
        'Quanto fedelmente i dati scritti dalla GPU tornano al gioco.', 'Relaxed (predefinito)',
        'Diagnostica', 'Statistiche dei fotogrammi nel registro (ogni 5 s)', 'Tempo GPU per passata nel registro',
        'Livelli di validazione Vulkan (serve il Vulkan SDK; molto più lento)', 'Variabili extra',
        'Coppie NOME=valore separate da spazi (elenco nel README).', 'Sistema',
        'Copia', 'Cancella', 'Sfoglia…', 'Apri',
        'Trucchi',
        'Patch del gioco per la versione 1.09, applicate all’avvio. Lasciale disattivate per una partita normale.',
        'Modifiche al gameplay',
        'Non morire mai (la salute non scende sotto 1 PS)',
        'I nemici non ti vedono (se non attaccati)',
        'I nemici non ti sentono',
        'La rivalsa non svanisce mai',
        'Controlla il nemico agganciato (R3; L3 per tornare; non con la telecamera libera)',
        'Niente rivalsa (i colpi non restituiscono salute)',
        'Telecamera più lontana dal personaggio',
        'Nessuna rotazione automatica della telecamera in movimento',
        'Corri con meno inclinazione dello stick (~70%)',
        'Fisica dei corpi stile Dark Souls (i cadaveri volano più lontano)',
        'Svuota la cache degli shader',
        'Se il gioco mostra solo uno schermo nero, di solito aiuta.',
        'Cache degli shader svuotata. Il prossimo avvio scatterà per qualche minuto mentre viene ricostruita.',
        'È disponibile la versione {}.',
        'Aggiorna',
        'Novità',
        'Installare ora la versione {}? Il launcher si chiude, la installa e si riapre. Salvataggi e impostazioni restano.',
        'Download della versione {}… {}%',
        'Aggiornamento non riuscito: {}',
        'Chiudi il gioco prima di aggiornare.',
        'Cerca aggiornamenti all’apertura del launcher',
        'Cerca aggiornamenti',
        'Hai l’ultima versione ({}).',
        'Impossibile cercare aggiornamenti: {}',
        'Impossibile installare l’aggiornamento. Scaricalo dalla pagina delle versioni.',
    ],
    'pl': [
        'Graj', 'Grafika', 'Ekran i FPS', 'Gra i efekty', 'Mody i łatki', 'Zaawansowane', 'Dziennik',
        'GRAJ', 'Zatrzymaj', 'natywny port · Windows', 'W grze: Insert lub L3+R3\notwiera menu portu.',
        'Sprawdzenie', 'Szybkie ustawienia', 'Liczba klatek', 'Upscaler', 'Profil', 'Wyjście', 'Pełny ekran',
        'CUSA03173 · wersja gry {}', 'Nie wybrano folderu gry', 'Wybierz folder gry (Gra i efekty)',
        '✓ Wersja gry {}: wszystkie łatki dostępne',
        '⚠ Wersja gry {}: działa w 30 FPS bez łatek społeczności (są dla wersji 1.09)',
        '✗ Brak eboot.bin w folderze gry (Gra i efekty)',
        '✓ Znaleziono zapisy w {}', '• Brak zapisów: gra utworzy je w {}',
        '✓ Karta graficzna: {}', '• Karta graficzna: nie sprawdzono', '• Sprawdzanie karty graficznej…',
        '✗ Nie znaleziono karty z Vulkan 1.3 (zaktualizuj sterownik)',
        '✓ Pliki FSR 4 zainstalowane', '• Brak plików FSR 4 (Grafika); do tego czasu używany jest FSR 3.1',
        'Najpierw wybierz folder gry.', 'Przygotowywanie gry; otworzy się we własnym oknie…',
        'Gra działa.', 'Ponowne uruchamianie z nowymi ustawieniami…',
        '\n— gra została zamknięta (kod {}) —\n', 'Nie udało się uruchomić: {}',
        'Wybierz folder gry z eboot.bin (CUSA03173).',
        'Zapisywane w bbport.ini; menu w grze (Insert lub L3+R3) zmienia te same wartości.',
        'Skalowanie',
        'Skalowanie czasowe z wektorami ruchu samej gry. FSR 4 wymaga swoich plików (poniżej) i GPU z INT8; w przeciwnym razie gra sama wraca do FSR 3.1.',
        'Profil jakości', 'Skala renderowania na oś: Quality renderuje w 1/1,5 rozdzielczości wyjścia.',
        'Rozdzielczość wyjścia', 'To, co tworzy upscaler; interfejs też jest rysowany w tym rozmiarze.',
        'Zmiana rozdzielczości na żywo',
        'Wył.: wyjścia inne niż 1080p ustawia łatka przy starcie (najszybciej; zmiana w grze ją restartuje). Wł.: zmieniaj wyjście i profil w grze bez restartu, kosztem wydajności.',
        'Wyostrzanie (RCAS)', 'Siła wyostrzania', 'Wektory ruchu obiektów',
        'Mniej smużenia na postaciach, ubraniach i broni; kosztuje około 10% FPS.',
        'Pliki FSR 4', 'Pobierz pliki FSR 4',
        'Z FireBurn/Q2RTX na GitHub (zbudowane z kodu AMD FidelityFX na licencji MIT), około 30 MB, do folderu fsr4_shaders portu.',
        'Zainstalowano: {} plików w {}.', 'Brakuje {} z {} plików w {}.', 'Pobieranie nie powiodło się: {}',
        'Szczegóły', 'Szczegółowość modeli (LOD)', 'Łatka gry (wersja 1.09).', 'Pokazuj licznik FPS',
        'FSR 4 (najlepsza jakość)', 'FSR 4.1.1 (wymaga plików fsr4_411)', 'FSR 3.1 (każde GPU)',
        'TAA (wygładzanie w natywnej rozdzielczości)', 'Wył.',
        'Automatycznie (wg karty)', 'Wył. (szybciej)', 'Wł. (zmiana bez restartu)',
        'Jak w grze', 'Najwyższa (−2)', 'Niższa (1)', 'Najniższa (2)',
        'Stosowane przy uruchomieniu gry.',
        'Łatki społeczności dla wersji 1.09. Bez limitu sprawia, że gra używa rzeczywistego czasu klatki. Inne wersje zawsze działają w 30 FPS (łatki by je uszkodziły).',
        'Limit FPS (tryb bez limitu)',
        'Powyżej około 120 FPS psuje się synchronizacja ruchu w grze (bieganie i przewroty zwalniają, fizyka i animacje mogą się sypać): wyższe limity na własne ryzyko.',
        'Klatki przed GPU',
        '1 utrzymuje równe tempo klatek; więcej może podnieść FPS, gdy ogranicza karta.',
        'Okno', 'Wyświetlanie', 'Zezwól na HDR', 'Gdy HDR jest włączony w Windows i obsługiwany przez ekran.',
        'Bez limitu (łatka czasu klatki)', '30 FPS (jak na PS4)',
        'Auto: odświeżanie ekranu, maks. 120 (zalecane)', 'Bez limitu',
        'Mailbox (niskie opóźnienie, bez rozrywania)', 'Immediate (z rozrywaniem)', '1 (domyślnie)', 'Bez ograniczenia',
        'Twoja gra to wersja {}: te opcje to łatki dla 1.09 i nie są stosowane; gra działa w 30 FPS. Zaktualizuj zrzut do 1.09, aby z nich korzystać.',
        'Twój zrzut gry, zapisy i łatki gry.', 'Gra', 'Folder gry', 'Wybierz folder z eboot.bin',
        'Twój własny zrzut CUSA03173 (eboot.bin, sce_module, sce_sys, dvdroot_ps4); wersja 1.09 dla łatek społeczności.',
        'Folder zapisów', 'Wybierz folder zapisów', 'Puste: {} (tam też jest pamięć podręczna shaderów).',
        'Język gry', 'Nazwa gracza', 'Tam, gdzie gra pokazuje nazwę PSN; puste: domyślna.',
        'Efekty', 'Aberracja chromatyczna', 'Głębia ostrości', 'Rozmycie ruchu', 'Okluzja otoczenia (SSAO)',
        'Własne wygładzanie gry', 'Cienie dynamicznych świateł', 'Odbicia w przestrzeni ekranu (nie było w oryginale)',
        'Dodatki', 'Pomiń logo i film wprowadzający', 'Wolna kamera (przytrzymaj Cross + L3; klawiatura Space + Z)',
        'Menu debugowania gry (lewy touchpad / Tab; wymaga czcionek debugowania)',
        'Efekty i dodatki to łatki dla wersji 1.09, stosowane przy starcie.',
        'Angielski', 'Rosyjski', 'Japoński', 'Francuski', 'Hiszpański', 'Niemiecki', 'Włoski',
        'Pliki gry nigdy nie są zmieniane: mody są nakładane przy starcie.', 'Mody', 'Wczytuj mody',
        'Mody z luźnych plików, każdy we własnym folderze (z dvdroot_ps4 albo chr\\, parts\\ … bezpośrednio).',
        'Folder modów', 'Wybierz folder modów', 'Puste: {}', 'Łatki zewnętrzne', 'Folder łatek',
        'Wybierz folder łatek', 'Pliki XML łatek shadPS4/GoldHEN dla 1.09. Puste: {}',
        'Odśwież', 'Brak modów w {}.', 'Niżej na liście wczytuje się później i wygrywa konflikty.',
        'Brak plików łatek dla 1.09.',
        'Opcje launchera, wydajność i diagnostyka.', 'Launcher', 'Język launchera',
        'Zadziała po ponownym otwarciu launchera.', 'Zamknij launcher po uruchomieniu gry',
        'Skrót na pulpicie', 'Folder portu', 'Utworzono skrót na pulpicie.', 'Wydajność',
        'Dwuetapowy potok GPU', 'Szybciej o 20–30%; wyłącz, jeśli gra jest niestabilna.',
        'Automatycznie (8+ wątków)', 'Wł.', 'Wył. (stabilniej)', 'Odczyty z GPU',
        'Jak dokładnie dane zapisane przez GPU wracają do gry.', 'Relaxed (domyślnie)',
        'Diagnostyka', 'Statystyki klatek w dzienniku (co 5 s)', 'Czas GPU na przebieg w dzienniku',
        'Warstwy walidacji Vulkan (wymaga Vulkan SDK; dużo wolniej)', 'Dodatkowe zmienne',
        'Pary NAZWA=wartość rozdzielone spacjami (lista w README).', 'Systemowy',
        'Kopiuj', 'Wyczyść', 'Przeglądaj…', 'Otwórz',
        'Kody',
        'Łatki gry dla wersji 1.09, stosowane przy starcie. Do zwykłej rozgrywki zostaw je wyłączone.',
        'Zmiany rozgrywki',
        'Nieśmiertelność (zdrowie nie spada poniżej 1 PZ)',
        'Wrogowie cię nie widzą (chyba że zaatakowani)',
        'Wrogowie cię nie słyszą',
        'Odzyskiwanie (Rally) nie zanika',
        'Sterowanie namierzonym wrogiem (R3; L3 powrót; nie z wolną kamerą)',
        'Bez odzyskiwania (ciosy nie oddają zdrowia)',
        'Kamera dalej od postaci',
        'Bez automatycznego obrotu kamery w ruchu',
        'Bieg przy mniejszym wychyleniu gałki (~70%)',
        'Fizyka ciał jak w Dark Souls (ciała odlatują dalej)',
        'Wyczyść pamięć shaderów',
        'Jeśli gra pokazuje tylko czarny ekran, zwykle to pomaga.',
        'Pamięć shaderów wyczyszczona. Następne uruchomienie przez kilka minut będzie się przycinać, aż się odbuduje.',
        'Dostępna jest wersja {}.',
        'Aktualizuj',
        'Co nowego',
        'Zainstalować teraz wersję {}? Launcher zamknie się, zainstaluje ją i otworzy ponownie. Zapisy i ustawienia zostaną zachowane.',
        'Pobieranie wersji {}… {}%',
        'Aktualizacja nie powiodła się: {}',
        'Zamknij grę przed aktualizacją.',
        'Sprawdzaj aktualizacje przy otwieraniu launchera',
        'Sprawdź aktualizacje',
        'Masz najnowszą wersję ({}).',
        'Nie udało się sprawdzić aktualizacji: {}',
        'Nie udało się zainstalować aktualizacji. Pobierz ją ze strony wydań.',
    ],
    'tr': [
        'Oyna', 'Grafik', 'Ekran ve FPS', 'Oyun ve efektler', 'Modlar ve yamalar', 'Gelişmiş', 'Günlük',
        'OYNA', 'Durdur', 'yerel port · Windows', 'Oyunda: Insert veya L3+R3\nport menüsünü açar.',
        'Hazırlık kontrolü', 'Hızlı ayarlar', 'Kare hızı', 'Ölçekleyici', 'Ön ayar', 'Çıkış', 'Tam ekran',
        'CUSA03173 · oyun sürümü {}', 'Oyun klasörü seçilmedi', 'Oyun klasörünü seçin (Oyun ve efektler)',
        '✓ Oyun sürümü {}: tüm yamalar kullanılabilir',
        '⚠ Oyun sürümü {}: topluluk yamaları olmadan 30 FPS çalışır (yamalar 1.09 için)',
        '✗ Oyun klasöründe eboot.bin yok (Oyun ve efektler)',
        '✓ Kayıtlar bulundu: {}', '• Henüz kayıt yok: oyun bunları şurada oluşturacak: {}',
        '✓ Ekran kartı: {}', '• Ekran kartı: kontrol edilmedi', '• Ekran kartı kontrol ediliyor…',
        '✗ Vulkan 1.3 destekli ekran kartı bulunamadı (sürücüyü güncelleyin)',
        '✓ FSR 4 dosyaları kurulu', '• FSR 4 dosyaları eksik (Grafik); bu arada FSR 3.1 kullanılıyor',
        'Önce oyun klasörünü seçin.', 'Oyun hazırlanıyor; kendi penceresinde açılacak…',
        'Oyun çalışıyor.', 'Yeni ayarlarla yeniden başlatılıyor…',
        '\n— oyun kapandı (kod {}) —\n', 'Başlatılamadı: {}',
        'eboot.bin içeren oyun klasörünü seçin (CUSA03173).',
        'bbport.ini içinde saklanır; oyun içi menü (Insert veya L3+R3) aynı değerleri değiştirir.',
        'Ölçekleme',
        'Oyunun kendi hareket vektörleriyle zamansal ölçekleme. FSR 4 için dosyaları (aşağıda) ve INT8 destekli bir GPU gerekir; aksi halde oyun kendiliğinden FSR 3.1’e döner.',
        'Kalite ön ayarı', 'Eksen başına render ölçeği: Quality, çıkış boyutunun 1/1,5’inde render eder.',
        'Çıkış çözünürlüğü', 'Ölçekleyicinin ürettiği boyut; arayüz de bu boyutta çizilir.',
        'Canlı çözünürlük değişimi',
        'Kapalı: 1080p dışındaki çıkışlar başlangıçta bir yamayla ayarlanır (en hızlısı; oyunda değiştirmek oyunu yeniden başlatır). Açık: çıkışı ve ön ayarı oyunda yeniden başlatmadan değiştirin, performans maliyetiyle.',
        'Keskinleştirme (RCAS)', 'Keskinlik gücü', 'Nesne hareket vektörleri',
        'Karakterlerde, kıyafetlerde ve silahlarda daha az iz; yaklaşık %10 FPS’e mal olur.',
        'FSR 4 dosyaları', 'FSR 4 dosyalarını indir',
        'GitHub’daki FireBurn/Q2RTX’ten (AMD’nin MIT lisanslı FidelityFX kaynağından derlenmiş), yaklaşık 30 MB, portun fsr4_shaders klasörüne.',
        'Kurulu: {} içinde {} dosya.', '{} dosyadan {} tanesi eksik: {}.', 'İndirme başarısız: {}',
        'Ayrıntı', 'Model ayrıntısı (LOD)', 'Bir oyun yaması (sürüm 1.09).', 'FPS sayacını göster',
        'FSR 4 (en iyi kalite)', 'FSR 4.1.1 (fsr4_411 dosyaları gerekir)', 'FSR 3.1 (her GPU)',
        'TAA (yerel çözünürlükte kenar yumuşatma)', 'Kapalı',
        'Otomatik (ekran kartına göre)', 'Kapalı (daha hızlı)', 'Açık (yeniden başlatmadan değiştir)',
        'Oyundaki gibi', 'En yüksek (−2)', 'Daha düşük (1)', 'En düşük (2)',
        'Oyun başlarken uygulanır.',
        'Oyun sürümü 1.09 için topluluk yamaları. Sınırsız mod, oyunun gerçek kare süresini kullanmasını sağlar. Diğer sürümler her zaman 30 FPS çalışır (yamalar onları bozar).',
        'FPS sınırı (sınırsız mod)',
        'Yaklaşık 120 FPS üzerinde oyunun hareket zamanlaması bozulur (koşma ve yuvarlanma yavaşlar, fizik ve animasyonlar bozulabilir): daha yüksek sınırlar sizin sorumluluğunuzdadır.',
        'GPU’nun önündeki kareler',
        '1 kare akışını düzenli tutar; daha fazlası ekran kartı darboğazken FPS’i artırabilir.',
        'Pencere', 'Sunum', 'HDR çıkışına izin ver', 'Windows’ta HDR açık ve ekran destekliyorsa.',
        'Sınırsız (kare süresi yaması)', '30 FPS (PS4’teki gibi)',
        'Otomatik: ekran yenileme hızı, en fazla 120 (önerilen)', 'Sınır yok',
        'Mailbox (düşük gecikme, yırtılma yok)', 'Immediate (yırtılmalı)', '1 (varsayılan)', 'Sınırsız',
        'Oyununuz {} sürümü: bu seçenekler 1.09 yamalarıdır ve uygulanmaz; oyun 30 FPS çalışır. Kullanmak için dökümünüzü 1.09’a güncelleyin.',
        'Oyun dökümünüz, kayıtlarınız ve oyun yamaları.', 'Oyun', 'Oyun klasörü', 'eboot.bin içeren klasörü seçin',
        'Kendi CUSA03173 dökümünüz (eboot.bin, sce_module, sce_sys, dvdroot_ps4); topluluk yamaları için sürüm 1.09.',
        'Kayıt klasörü', 'Kayıt klasörünü seçin', 'Boş: {} (shader önbelleği de orada tutulur).',
        'Oyun dili', 'Oyuncu adı', 'Oyunun PSN adını gösterdiği yerler; boş: varsayılan.',
        'Efektler', 'Renk sapması', 'Alan derinliği', 'Hareket bulanıklığı', 'Ortam perdeleme (SSAO)',
        'Oyunun kendi kenar yumuşatması', 'Dinamik ışık gölgeleri', 'Ekran alanı yansımaları (orijinalde yok)',
        'Ekstralar', 'Giriş logolarını ve videosunu atla', 'Serbest kamera (Cross + L3 basılı tutun; klavye Space + Z)',
        'Oyun hata ayıklama menüsü (sol dokunmatik yüzey / Tab; hata ayıklama yazı tipleri gerekir)',
        'Efektler ve ekstralar 1.09 sürümü için oyun yamalarıdır, başlangıçta uygulanır.',
        'İngilizce', 'Rusça', 'Japonca', 'Fransızca', 'İspanyolca', 'Almanca', 'İtalyanca',
        'Oyun dosyaları asla değiştirilmez: modlar başlangıçta üzerlerine eklenir.', 'Modlar', 'Modları yükle',
        'Dosya modları, her biri kendi klasöründe (dvdroot_ps4 ile ya da doğrudan chr\\, parts\\ …).',
        'Mod klasörü', 'Mod klasörünü seçin', 'Boş: {}', 'Üçüncü taraf yamalar', 'Yama klasörü',
        'Yama klasörünü seçin', '1.09 için shadPS4/GoldHEN XML yama dosyaları. Boş: {}',
        'Yenile', '{} içinde henüz mod yok.', 'Listede daha aşağıdaki sonra yüklenir ve çakışmalarda kazanır.',
        '1.09 için henüz yama dosyası yok.',
        'Başlatıcı seçenekleri, performans ve tanılama.', 'Başlatıcı', 'Başlatıcı dili',
        'Başlatıcı yeniden açıldığında uygulanır.', 'Oyun başlayınca başlatıcıyı kapat',
        'Masaüstü kısayolu', 'Port klasörü', 'Masaüstünde kısayol oluşturuldu.', 'Performans',
        'İki aşamalı GPU hattı', '%20–30 daha hızlı; oyun kararsızsa kapatın.',
        'Otomatik (8+ iş parçacığı)', 'Açık', 'Kapalı (daha kararlı)', 'GPU geri okumaları',
        'GPU’nun yazdığı verilerin oyuna ne kadar doğru geri döndüğü.', 'Relaxed (varsayılan)',
        'Tanılama', 'Günlükte kare istatistikleri (5 sn’de bir)', 'Günlükte geçiş başına GPU süresi',
        'Vulkan doğrulama katmanları (Vulkan SDK gerekir; çok daha yavaş)', 'Ek değişkenler',
        'Boşlukla ayrılmış AD=değer çiftleri (liste README’de).', 'Sistem',
        'Kopyala', 'Temizle', 'Gözat…', 'Aç',
        'Hileler',
        'Sürüm 1.09 için oyun yamaları, başlangıçta uygulanır. Normal oynanış için kapalı bırakın.',
        'Oynanış ayarları',
        'Asla ölme (can 1’in altına düşmez)',
        'Düşmanlar seni görmez (saldırılmadıkça)',
        'Düşmanlar seni duymaz',
        'Rally hiç azalmaz',
        'Hedeflenen düşmanı kontrol et (R3; geri dönmek için L3; serbest kamerayla olmaz)',
        'Rally yok (vuruşlar can geri vermez)',
        'Kamera karakterden daha uzakta',
        'Hareket ederken kamera kendiliğinden dönmez',
        'Daha az çubuk eğimiyle koş (~%70)',
        'Dark Souls tarzı ragdoll fiziği (cesetler daha uzağa uçar)',
        'Shader önbelleğini temizle',
        'Oyun yalnızca siyah ekran gösteriyorsa bu genellikle işe yarar.',
        'Shader önbelleği temizlendi. Sonraki açılış, önbellek yeniden oluşurken birkaç dakika takılabilir.',
        '{} sürümü çıktı.',
        'Güncelle',
        'Yenilikler',
        '{} sürümü şimdi kurulsun mu? Başlatıcı kapanır, sürümü kurar ve yeniden açılır. Kayıtlar ve ayarlar korunur.',
        '{} sürümü indiriliyor… %{}',
        'Güncelleme başarısız: {}',
        'Güncellemeden önce oyunu kapatın.',
        'Başlatıcı açılırken güncellemeleri denetle',
        'Güncellemeleri denetle',
        'En son sürüme sahipsiniz ({}).',
        'Güncellemeler denetlenemedi: {}',
        'Güncelleme kurulamadı. Sürümler sayfasından indirin.',
    ],
    'zh': [
        '开始', '图形', '显示与帧率', '游戏与效果', '模组与补丁', '高级', '日志',
        '开始游戏', '停止', '原生移植 · Windows', '游戏中：Insert 或 L3+R3\n打开移植版菜单。',
        '就绪检查', '快速设置', '帧率', '超分辨率', '预设', '输出', '全屏',
        'CUSA03173 · 游戏版本 {}', '未设置游戏文件夹', '请选择游戏文件夹（游戏与效果）',
        '✓ 游戏版本 {}：所有补丁可用',
        '⚠ 游戏版本 {}：不含社区补丁，以 30 FPS 运行（补丁适用于 1.09）',
        '✗ 游戏文件夹中没有 eboot.bin（游戏与效果）',
        '✓ 在 {} 找到存档', '• 暂无存档：游戏会在 {} 中创建',
        '✓ 显卡：{}', '• 显卡：未检查', '• 正在检查显卡…',
        '✗ 未找到支持 Vulkan 1.3 的显卡（请更新驱动）',
        '✓ 已安装 FSR 4 文件', '• 缺少 FSR 4 文件（图形）；暂时使用 FSR 3.1',
        '请先选择游戏文件夹。', '正在准备游戏，将在单独的窗口中打开…',
        '游戏正在运行。', '正在以新设置重新启动…',
        '\n— 游戏已退出（代码 {}）—\n', '无法启动：{}',
        '请选择包含 eboot.bin 的游戏文件夹（CUSA03173）。',
        '保存在 bbport.ini 中；游戏内菜单（Insert 或 L3+R3）会修改相同的值。',
        '超分辨率',
        '使用游戏自身运动矢量的时间性超分辨率。FSR 4 需要其文件（见下方）和支持 INT8 的显卡；否则游戏会自动改用 FSR 3.1。',
        '画质预设', '每轴渲染比例：Quality 以输出尺寸的 1/1.5 渲染。',
        '输出分辨率', '超分辨率生成的尺寸；界面也以此尺寸绘制。',
        '实时切换分辨率',
        '关闭：1080p 以外的输出在启动时由补丁设置（最快；在游戏中更改会重启游戏）。开启：在游戏中更改输出和预设无需重启，但有性能开销。',
        '锐化 (RCAS)', '锐化强度', '物体运动矢量',
        '减少角色、服装和武器上的拖影；约损失 10% 帧率。',
        'FSR 4 文件', '下载 FSR 4 文件',
        '来自 GitHub 上的 FireBurn/Q2RTX（由 AMD 采用 MIT 许可的 FidelityFX 源码构建），约 30 MB，放入移植版的 fsr4_shaders 文件夹。',
        '已安装：{} 个文件，位于 {}。', '{} 中缺少 {} 个文件中的 {} 个。', '下载失败：{}',
        '细节', '模型细节 (LOD)', '游戏补丁（版本 1.09）。', '显示帧率计数器',
        'FSR 4（最佳画质）', 'FSR 4.1.1（需要 fsr4_411 文件）', 'FSR 3.1（任何显卡）',
        'TAA（原生分辨率抗锯齿）', '关闭',
        '自动（根据显卡）', '关闭（更快）', '开启（无需重启即可更改）',
        '与游戏相同', '最高 (−2)', '较低 (1)', '最低 (2)',
        '在游戏启动时应用。',
        '适用于游戏版本 1.09 的社区补丁。不限帧会让游戏使用真实帧时间。其他版本始终以 30 FPS 运行（补丁会损坏它们）。',
        '帧率上限（不限帧模式）',
        '超过约 120 FPS 时游戏的移动计时会出错（奔跑和翻滚变慢，物理和动画可能异常）：更高的上限风险自负。',
        '领先 GPU 的帧数',
        '1 可保持帧节奏平稳；显卡成为瓶颈时，更大的值可能提高帧率。',
        '窗口', '呈现方式', '允许 HDR 输出', '在 Windows 中开启 HDR 且显示器支持时。',
        '不限帧（帧时间补丁）', '30 FPS（与 PS4 相同）',
        '自动：显示器刷新率，最高 120（推荐）', '不限制',
        'Mailbox（低延迟，无撕裂）', 'Immediate（有撕裂）', '1（默认）', '不限',
        '你的游戏是 {} 版本：这些选项是 1.09 的补丁，不会生效；游戏以 30 FPS 运行。将游戏更新到 1.09 后即可使用。',
        '你的游戏转储、存档和游戏补丁。', '游戏', '游戏文件夹', '选择包含 eboot.bin 的文件夹',
        '你自己的 CUSA03173 转储（eboot.bin、sce_module、sce_sys、dvdroot_ps4）；社区补丁需要 1.09 版本。',
        '存档文件夹', '选择存档文件夹', '为空：{}（着色器缓存也保存在此）。',
        '游戏语言', '玩家名称', '游戏显示 PSN 名称的位置；为空：默认。',
        '效果', '色差', '景深', '动态模糊', '环境光遮蔽 (SSAO)',
        '游戏自带抗锯齿', '动态光源阴影', '屏幕空间反射（原版没有）',
        '附加', '跳过开场标志和影片', '自由镜头（按住 Cross + L3；键盘 Space + Z）',
        '游戏调试菜单（左触摸板 / Tab；需要调试字体）',
        '效果和附加项是适用于 1.09 版本的游戏补丁，在启动时应用。',
        '英语', '俄语', '日语', '法语', '西班牙语', '德语', '意大利语',
        '游戏文件永远不会被修改：模组在启动时叠加。', '模组', '加载模组',
        '散装文件模组，每个放在单独的文件夹中（含 dvdroot_ps4，或直接放 chr\\、parts\\ …）。',
        '模组文件夹', '选择模组文件夹', '为空：{}', '第三方补丁', '补丁文件夹',
        '选择补丁文件夹', '适用于 1.09 的 shadPS4/GoldHEN XML 补丁文件。为空：{}',
        '刷新', '{} 中还没有模组。', '列表中越靠下越晚加载，冲突时优先。',
        '还没有适用于 1.09 的补丁文件。',
        '启动器选项、性能开关和诊断。', '启动器', '启动器语言',
        '重新打开启动器后生效。', '游戏启动时关闭启动器',
        '桌面快捷方式', '移植版文件夹', '已在桌面创建快捷方式。', '性能',
        '两阶段 GPU 流水线', '快 20–30%；如果游戏不稳定请关闭。',
        '自动（8 线程以上）', '开启', '关闭（更稳定）', 'GPU 回读',
        'GPU 写入的数据返回给游戏的精确程度。', 'Relaxed（默认）',
        '诊断', '在日志中显示帧统计（每 5 秒）', '在日志中显示每个通道的 GPU 时间',
        'Vulkan 验证层（需要 Vulkan SDK；会慢很多）', '额外变量',
        '以空格分隔的 名称=值 对（列表见 README）。', '跟随系统',
        '复制', '清除', '浏览…', '打开',
        '作弊',
        '适用于 1.09 版本的游戏补丁，在启动时应用。正常游玩请保持关闭。',
        '玩法调整',
        '永不死亡（生命值不低于 1）',
        '敌人看不见你（除非被攻击）',
        '敌人听不见你',
        '回血（Rally）不会消退',
        '控制锁定的敌人（R3；L3 返回；不能与自由镜头同时使用）',
        '无回血（攻击不恢复生命值）',
        '镜头离角色更远',
        '移动时镜头不自动旋转',
        '摇杆推得更少即可奔跑（约 70%）',
        'Dark Souls 式布娃娃物理（尸体飞得更远）',
        '清除着色器缓存',
        '如果游戏只显示黑屏，这通常能解决。',
        '着色器缓存已清除。下次启动的前几分钟会因重建缓存而卡顿。',
        '新版本 {} 已发布。',
        '更新',
        '更新内容',
        '现在安装版本 {} 吗？启动器会关闭、完成安装后重新打开。存档和设置会保留。',
        '正在下载版本 {}… {}%',
        '更新失败：{}',
        '请先关闭游戏再更新。',
        '打开启动器时检查更新',
        '检查更新',
        '已是最新版本（{}）。',
        '无法检查更新：{}',
        '无法安装更新。请从发布页面下载。',
    ],
    'ja': [
        'プレイ', 'グラフィック', '表示とFPS', 'ゲームとエフェクト', 'MODとパッチ', '詳細設定', 'ログ',
        'プレイ', '停止', 'ネイティブ移植 · Windows', 'ゲーム中：Insert または L3+R3\nで移植版メニューを開きます。',
        '準備チェック', 'クイック設定', 'フレームレート', 'アップスケーラー', 'プリセット', '出力', 'フルスクリーン',
        'CUSA03173 · ゲームバージョン {}', 'ゲームフォルダー未設定', 'ゲームフォルダーを選択してください（ゲームとエフェクト）',
        '✓ ゲームバージョン {}：すべてのパッチを使用できます',
        '⚠ ゲームバージョン {}：コミュニティパッチなしの 30 FPS で動作します（パッチは 1.09 用）',
        '✗ ゲームフォルダーに eboot.bin がありません（ゲームとエフェクト）',
        '✓ セーブデータが見つかりました：{}', '• セーブデータはまだありません：ゲームが {} に作成します',
        '✓ グラフィックカード：{}', '• グラフィックカード：未確認', '• グラフィックカードを確認中…',
        '✗ Vulkan 1.3 対応のグラフィックカードが見つかりません（ドライバーを更新してください）',
        '✓ FSR 4 ファイルはインストール済み', '• FSR 4 ファイルがありません（グラフィック）。当面は FSR 3.1 を使用します',
        '先にゲームフォルダーを選択してください。', 'ゲームを準備しています。専用のウィンドウで開きます…',
        'ゲーム実行中。', '新しい設定で再起動しています…',
        '\n— ゲームが終了しました（コード {}）—\n', '起動できませんでした：{}',
        'eboot.bin のあるゲームフォルダーを選択してください（CUSA03173）。',
        'bbport.ini に保存されます。ゲーム内メニュー（Insert または L3+R3）でも同じ値を変更できます。',
        'アップスケーリング',
        'ゲーム自身のモーションベクトルを使うテンポラルアップスケーリング。FSR 4 にはファイル（下記）と INT8 対応 GPU が必要です。ない場合は自動で FSR 3.1 になります。',
        '画質プリセット', '軸ごとの描画スケール：Quality は出力サイズの 1/1.5 で描画します。',
        '出力解像度', 'アップスケーラーが出力するサイズ。UI もこのサイズで描画されます。',
        '解像度のライブ変更',
        'オフ：1080p 以外の出力は起動時にパッチで設定（最速。ゲーム内で変更すると再起動）。オン：再起動なしでゲーム内から出力とプリセットを変更できますが、負荷が増えます。',
        'シャープ化 (RCAS)', 'シャープの強さ', 'オブジェクトのモーションベクトル',
        'キャラクター・衣服・武器の残像を減らします。FPS が約 10% 下がります。',
        'FSR 4 ファイル', 'FSR 4 ファイルをダウンロード',
        'GitHub の FireBurn/Q2RTX から（AMD の MIT ライセンスの FidelityFX ソースからビルド）、約 30 MB、移植版の fsr4_shaders フォルダーへ。',
        'インストール済み：{} ファイル（{}）。', '{} 中 {} ファイルが {} にありません。', 'ダウンロードに失敗しました：{}',
        'ディテール', 'モデルの詳細度 (LOD)', 'ゲームパッチ（バージョン 1.09）。', 'FPS カウンターを表示',
        'FSR 4（最高画質）', 'FSR 4.1.1（fsr4_411 ファイルが必要）', 'FSR 3.1（すべての GPU）',
        'TAA（ネイティブ解像度のアンチエイリアス）', 'オフ',
        '自動（グラフィックカードに応じて）', 'オフ（高速）', 'オン（再起動なしで変更）',
        'ゲームのまま', '最高 (−2)', '低め (1)', '最低 (2)',
        'ゲーム起動時に適用されます。',
        'ゲームバージョン 1.09 用のコミュニティパッチ。無制限ではゲームが実際のフレーム時間を使います。他のバージョンは常に 30 FPS で動作します（パッチで壊れるため）。',
        'フレームレート上限（無制限モード）',
        '約 120 FPS を超えるとゲームの移動タイミングが崩れます（走りや回避が遅くなり、物理やアニメーションが乱れることがあります）。高い上限は自己責任で。',
        'GPU より先行するフレーム数',
        '1 はフレームペースを安定させます。GPU がボトルネックの場合、増やすと FPS が上がることがあります。',
        'ウィンドウ', '表示方式', 'HDR 出力を許可', 'Windows で HDR がオンで、ディスプレイが対応している場合。',
        '無制限（フレーム時間パッチ）', '30 FPS（PS4 と同じ）',
        '自動：ディスプレイのリフレッシュレート、最大 120（推奨）', '上限なし',
        'Mailbox（低遅延・ティアリングなし）', 'Immediate（ティアリングあり）', '1（既定）', '無制限',
        'お使いのゲームはバージョン {} です。これらは 1.09 用のパッチのため適用されず、ゲームは 30 FPS で動作します。使うにはダンプを 1.09 に更新してください。',
        'ゲームのダンプ、セーブデータ、ゲームパッチ。', 'ゲーム', 'ゲームフォルダー', 'eboot.bin のあるフォルダーを選択',
        'ご自身の CUSA03173 のダンプ（eboot.bin、sce_module、sce_sys、dvdroot_ps4）。コミュニティパッチには 1.09 が必要です。',
        'セーブフォルダー', 'セーブフォルダーを選択', '空欄：{}（シェーダーキャッシュもここに保存されます）。',
        'ゲームの言語', 'プレイヤー名', 'ゲームが PSN 名を表示する箇所。空欄：既定。',
        'エフェクト', '色収差', '被写界深度', 'モーションブラー', 'アンビエントオクルージョン (SSAO)',
        'ゲーム本来のアンチエイリアス', '動的ライトの影', 'スクリーンスペース反射（オリジナルにはなし）',
        'その他', 'オープニングのロゴとムービーをスキップ', 'フリーカメラ（Cross + L3 長押し、キーボードは Space + Z）',
        'ゲームのデバッグメニュー（左タッチパッド / Tab。デバッグ用フォントが必要）',
        'エフェクトとその他はバージョン 1.09 用のゲームパッチで、起動時に適用されます。',
        '英語', 'ロシア語', '日本語', 'フランス語', 'スペイン語', 'ドイツ語', 'イタリア語',
        'ゲームファイルは変更されません。MOD は起動時に重ねて読み込まれます。', 'MOD', 'MOD を読み込む',
        'ファイル形式の MOD。それぞれ専用フォルダーに（dvdroot_ps4 付き、または chr\\、parts\\ … を直接）。',
        'MOD フォルダー', 'MOD フォルダーを選択', '空欄：{}', 'サードパーティ製パッチ', 'パッチフォルダー',
        'パッチフォルダーを選択', '1.09 用の shadPS4/GoldHEN XML パッチファイル。空欄：{}',
        '更新', '{} にはまだ MOD がありません。', 'リストの下にあるものほど後に読み込まれ、競合時に優先されます。',
        '1.09 用のパッチファイルはまだありません。',
        'ランチャーの設定、パフォーマンス、診断。', 'ランチャー', 'ランチャーの言語',
        'ランチャーを再度開いたときに適用されます。', 'ゲーム起動時にランチャーを閉じる',
        'デスクトップのショートカット', '移植版フォルダー', 'デスクトップにショートカットを作成しました。', 'パフォーマンス',
        '2 段階 GPU パイプライン', '20〜30% 高速。ゲームが不安定ならオフにしてください。',
        '自動（8 スレッド以上）', 'オン', 'オフ（安定）', 'GPU リードバック',
        'GPU が書き込んだデータをどれだけ正確にゲームへ戻すか。', 'Relaxed（既定）',
        '診断', 'ログにフレーム統計（5 秒ごと）', 'ログにパスごとの GPU 時間',
        'Vulkan 検証レイヤー（Vulkan SDK が必要。大幅に遅くなります）', '追加の変数',
        'スペース区切りの 名前=値 のペア（一覧は README）。', 'システム',
        'コピー', 'クリア', '参照…', '開く',
        'チート',
        'バージョン 1.09 用のゲームパッチで、起動時に適用されます。通常のプレイではオフのままにしてください。',
        'ゲームプレイの調整',
        '死なない（HP は 1 未満にならない）',
        '敵に見つからない（攻撃しない限り）',
        '敵に聞こえない',
        'リゲインが減らない',
        'ロックオンした敵を操作（R3、L3 で戻る、フリーカメラとは併用不可）',
        'リゲインなし（攻撃で HP が戻らない）',
        'カメラをキャラクターから遠くする',
        '移動中のカメラ自動回転なし',
        'スティックの傾きが少なくても走る（約 70%）',
        'ダークソウル風のラグドール物理（死体が遠くまで飛ぶ）',
        'シェーダーキャッシュを消去',
        'ゲームが黒い画面のままのときは、たいていこれで直ります。',
        'シェーダーキャッシュを消去しました。次回起動時は再構築のため数分間カクつきます。',
        'バージョン {} が利用できます。',
        '更新',
        '新機能',
        'バージョン {} を今すぐインストールしますか？ランチャーが閉じてインストールし、再び開きます。セーブデータと設定はそのままです。',
        'バージョン {} をダウンロード中… {}%',
        '更新に失敗しました：{}',
        '更新する前にゲームを終了してください。',
        'ランチャー起動時に更新を確認',
        '更新を確認',
        '最新バージョンです（{}）。',
        '更新を確認できませんでした：{}',
        '更新をインストールできませんでした。リリースページからダウンロードしてください。',
    ],
    'ko': [
        '플레이', '그래픽', '디스플레이 및 FPS', '게임 및 효과', '모드 및 패치', '고급', '로그',
        '플레이', '중지', '네이티브 포트 · Windows', '게임 중: Insert 또는 L3+R3\n포트 메뉴 열기.',
        '준비 상태', '빠른 설정', '프레임 속도', '업스케일러', '프리셋', '출력', '전체 화면',
        'CUSA03173 · 게임 버전 {}', '게임 폴더가 지정되지 않음', '게임 폴더를 선택하세요 (게임 및 효과)',
        '✓ 게임 버전 {}: 모든 패치 사용 가능',
        '⚠ 게임 버전 {}: 커뮤니티 패치 없이 30 FPS로 실행 (패치는 1.09용)',
        '✗ 게임 폴더에 eboot.bin이 없음 (게임 및 효과)',
        '✓ 세이브 발견: {}', '• 아직 세이브 없음: 게임이 {}에 만듭니다',
        '✓ 그래픽 카드: {}', '• 그래픽 카드: 확인 안 됨', '• 그래픽 카드 확인 중…',
        '✗ Vulkan 1.3 그래픽 카드를 찾을 수 없음 (드라이버를 업데이트하세요)',
        '✓ FSR 4 파일 설치됨', '• FSR 4 파일 없음 (그래픽); 그동안 FSR 3.1 사용',
        '먼저 게임 폴더를 선택하세요.', '게임 준비 중; 별도 창에서 열립니다…',
        '게임 실행 중.', '새 설정으로 다시 시작하는 중…',
        '\n— 게임이 종료됨 (코드 {}) —\n', '시작할 수 없음: {}',
        'eboot.bin이 있는 게임 폴더를 선택하세요 (CUSA03173).',
        'bbport.ini에 저장됩니다. 게임 내 메뉴(Insert 또는 L3+R3)에서도 같은 값을 바꿉니다.',
        '업스케일링',
        '게임 자체의 모션 벡터를 사용한 시간적 업스케일링. FSR 4에는 파일(아래)과 INT8 지원 GPU가 필요하며, 없으면 게임이 자동으로 FSR 3.1을 사용합니다.',
        '품질 프리셋', '축별 렌더 배율: Quality는 출력 크기의 1/1.5로 렌더링합니다.',
        '출력 해상도', '업스케일러가 만드는 크기. UI도 이 크기로 그려집니다.',
        '실시간 해상도 변경',
        '끔: 1080p 외의 출력은 시작 시 패치로 설정 (가장 빠름, 게임에서 바꾸면 재시작). 켬: 재시작 없이 게임에서 출력과 프리셋 변경, 성능 비용 있음.',
        '선명화 (RCAS)', '선명도 강도', '오브젝트 모션 벡터',
        '캐릭터, 옷, 무기의 잔상이 줄어듭니다. FPS가 약 10% 감소합니다.',
        'FSR 4 파일', 'FSR 4 파일 다운로드',
        'GitHub의 FireBurn/Q2RTX에서 (AMD의 MIT 라이선스 FidelityFX 소스로 빌드), 약 30 MB, 포트의 fsr4_shaders 폴더로.',
        '설치됨: {}개 파일, 위치 {}.', '{}개 중 {}개 파일이 {}에 없음.', '다운로드 실패: {}',
        '디테일', '모델 디테일 (LOD)', '게임 패치 (버전 1.09).', 'FPS 카운터 표시',
        'FSR 4 (최고 품질)', 'FSR 4.1.1 (fsr4_411 파일 필요)', 'FSR 3.1 (모든 GPU)',
        'TAA (네이티브 해상도 안티에일리어싱)', '끔',
        '자동 (그래픽 카드에 따라)', '끔 (더 빠름)', '켬 (재시작 없이 변경)',
        '게임 그대로', '최고 (−2)', '낮게 (1)', '최저 (2)',
        '게임 시작 시 적용됩니다.',
        '게임 버전 1.09용 커뮤니티 패치. 제한 없음은 게임이 실제 프레임 시간을 사용하게 합니다. 다른 버전은 항상 30 FPS로 실행됩니다 (패치가 손상시키기 때문).',
        'FPS 상한 (제한 없음 모드)',
        '약 120 FPS를 넘으면 게임의 이동 타이밍이 깨집니다 (달리기와 구르기가 느려지고 물리와 애니메이션이 이상해질 수 있음). 더 높은 상한은 본인 책임입니다.',
        'GPU보다 앞선 프레임',
        '1은 프레임 페이싱을 고르게 유지합니다. 그래픽 카드가 병목이면 더 높이면 FPS가 오를 수 있습니다.',
        '창', '표시 방식', 'HDR 출력 허용', 'Windows에서 HDR이 켜져 있고 디스플레이가 지원할 때.',
        '제한 없음 (프레임 시간 패치)', '30 FPS (PS4와 동일)',
        '자동: 디스플레이 주사율, 최대 120 (권장)', '제한 없음',
        'Mailbox (낮은 지연, 티어링 없음)', 'Immediate (티어링 있음)', '1 (기본)', '무제한',
        '게임 버전이 {}입니다. 이 옵션들은 1.09용 패치라 적용되지 않으며 게임은 30 FPS로 실행됩니다. 사용하려면 덤프를 1.09로 업데이트하세요.',
        '게임 덤프, 세이브, 게임 패치.', '게임', '게임 폴더', 'eboot.bin이 있는 폴더 선택',
        '직접 만든 CUSA03173 덤프 (eboot.bin, sce_module, sce_sys, dvdroot_ps4). 커뮤니티 패치에는 1.09가 필요합니다.',
        '세이브 폴더', '세이브 폴더 선택', '비어 있음: {} (셰이더 캐시도 여기에 저장됩니다).',
        '게임 언어', '플레이어 이름', '게임이 PSN 이름을 표시하는 곳. 비어 있으면 기본값.',
        '효과', '색수차', '피사계 심도', '모션 블러', '앰비언트 오클루전 (SSAO)',
        '게임 자체 안티에일리어싱', '동적 조명 그림자', '화면 공간 반사 (원작에 없음)',
        '추가 기능', '시작 로고와 영상 건너뛰기', '자유 카메라 (Cross + L3 누르고 있기, 키보드 Space + Z)',
        '게임 디버그 메뉴 (왼쪽 터치패드 / Tab, 디버그 글꼴 필요)',
        '효과와 추가 기능은 버전 1.09용 게임 패치이며 시작 시 적용됩니다.',
        '영어', '러시아어', '일본어', '프랑스어', '스페인어', '독일어', '이탈리아어',
        '게임 파일은 절대 바뀌지 않습니다. 모드는 시작 시 위에 덧씌워집니다.', '모드', '모드 불러오기',
        '파일 형태 모드, 각각 자체 폴더에 (dvdroot_ps4 포함 또는 chr\\, parts\\ … 직접).',
        '모드 폴더', '모드 폴더 선택', '비어 있음: {}', '서드파티 패치', '패치 폴더',
        '패치 폴더 선택', '1.09용 shadPS4/GoldHEN XML 패치 파일. 비어 있음: {}',
        '새로 고침', '{}에 아직 모드가 없습니다.', '목록에서 아래쪽일수록 나중에 불러오며 충돌 시 우선합니다.',
        '아직 1.09용 패치 파일이 없습니다.',
        '런처 옵션, 성능 스위치, 진단.', '런처', '런처 언어',
        '런처를 다시 열면 적용됩니다.', '게임 시작 시 런처 닫기',
        '바탕화면 바로가기', '포트 폴더', '바탕화면에 바로가기를 만들었습니다.', '성능',
        '2단계 GPU 파이프라인', '20–30% 더 빠름. 게임이 불안정하면 끄세요.',
        '자동 (8스레드 이상)', '켬', '끔 (더 안정적)', 'GPU 리드백',
        'GPU가 쓴 데이터를 게임에 얼마나 정확히 되돌려 주는지.', 'Relaxed (기본)',
        '진단', '로그에 프레임 통계 (5초마다)', '로그에 패스별 GPU 시간',
        'Vulkan 검증 레이어 (Vulkan SDK 필요, 훨씬 느림)', '추가 변수',
        '공백으로 구분한 이름=값 쌍 (목록은 README).', '시스템',
        '복사', '지우기', '찾아보기…', '열기',
        '치트',
        '버전 1.09용 게임 패치로 시작 시 적용됩니다. 일반 플레이에서는 꺼 두세요.',
        '게임플레이 조정',
        '절대 죽지 않음 (체력이 1 아래로 내려가지 않음)',
        '적이 보지 못함 (공격하지 않는 한)',
        '적이 듣지 못함',
        '리게인이 사라지지 않음',
        '조준한 적 조종 (R3, L3로 복귀, 자유 카메라와 함께 사용 불가)',
        '리게인 없음 (공격해도 체력이 회복되지 않음)',
        '카메라를 캐릭터에서 더 멀리',
        '이동 중 카메라 자동 회전 없음',
        '스틱을 덜 기울여도 달리기 (약 70%)',
        '다크 소울 스타일 래그돌 물리 (시체가 더 멀리 날아감)',
        '셰이더 캐시 지우기',
        '게임이 검은 화면만 보이면 보통 이것으로 해결됩니다.',
        '셰이더 캐시를 지웠습니다. 다음 실행은 캐시를 다시 만드는 몇 분 동안 끊길 수 있습니다.',
        '버전 {}을(를) 사용할 수 있습니다.',
        '업데이트',
        '새로운 기능',
        '지금 버전 {}을(를) 설치할까요? 런처가 닫히고 설치한 뒤 다시 열립니다. 세이브와 설정은 유지됩니다.',
        '버전 {} 다운로드 중… {}%',
        '업데이트 실패: {}',
        '업데이트하기 전에 게임을 종료하세요.',
        '런처를 열 때 업데이트 확인',
        '업데이트 확인',
        '최신 버전입니다 ({}).',
        '업데이트를 확인할 수 없습니다: {}',
        '업데이트를 설치할 수 없습니다. 릴리스 페이지에서 다운로드하세요.',
    ],
}

LANGUAGE_NAMES = [('', ('System', 'Как в системе')), ('en', ('English',)), ('ru', ('Русский',)),
                  ('ar', ('العربية',)), ('es', ('Español',)), ('pt', ('Português (Brasil)',)),
                  ('fr', ('Français',)), ('de', ('Deutsch',)), ('it', ('Italiano',)),
                  ('pl', ('Polski',)), ('tr', ('Türkçe',)), ('zh', ('简体中文',)), ('ja', ('日本語',)),
                  ('ko', ('한국어',))]
# Windows primary language ids (GetUserDefaultUILanguage() & 0x3ff) -> launcher language.
WINDOWS_LANGUAGES = {0x19: 'ru', 0x01: 'ar', 0x0a: 'es', 0x16: 'pt', 0x0c: 'fr', 0x07: 'de', 0x10: 'it',
                     0x15: 'pl', 0x1f: 'tr', 0x04: 'zh', 0x11: 'ja', 0x12: 'ko'}

from bbport_lang_more import MORE, MORE_KEYS  # noqa: E402 (texts added later, Russian included)

_tables = {}


def table(language):
    """English text -> translation for one language ({} for English)."""
    if language not in _tables:
        texts = TRANSLATIONS.get(language)
        if texts and len(texts) != len(KEYS):
            raise ValueError(f'launcher translation {language}: {len(texts)} texts for {len(KEYS)} keys')
        more = MORE.get(language)
        if more and len(more) != len(MORE_KEYS):
            raise ValueError(f'launcher translation {language}: {len(more)} texts for {len(MORE_KEYS)} new keys')
        _tables[language] = {**(dict(zip(KEYS, texts)) if texts else {}),
                             **(dict(zip(MORE_KEYS, more)) if more else {})}
    return _tables[language]
